### PR TITLE
Added  feature closing the upload document component after clicking ouside  

### PR DESCRIPTION
**Pull request by prathamesh424**
Added  feature closing the upload document component after clicking ouside 
[Fixed:issue #1231 ]
As the issue assign to  me but someone completed the other work but not added the closing of uploading component after clicking outside the component . 

Result : after issue solve

https://github.com/user-attachments/assets/8db6e88c-8bfa-4e9a-a679-459631bc987e

### CODE REVIEW

**Comment by prathamesh424** [comment]
@dartpain  @ManishMadan2882 check out changes

**Comment by ManishMadan2882** [comment]
@prathamesh424 
The issue was focused on creating a Base Modal component, like a wrapper component which can be reused by other modal components, the base modal should match the styling of Upload modal as mentioned by @pabik in #1231 and it should get closed on clicking outside the modal.
Thanks.

**Comment by prathamesh424** [comment]
@ManishMadan2882 is this PR getting marged

**Comment by dartpain** [comment]
@prathamesh424 @ManishMadan2882 is the maintainer of this project.

**Pull request closed without merging**
