### PR TITLE
Enhancement: Added loading state for conversation list

### LINKED ISSUE #1342: 🐛 Bug Report: Enhancement - Add Loader Icon for Fetching List of Conversations
### 📜 Description

The current implementation for loading the list of conversations in the sidebar lacks visual feedback for users. When the page is initially loaded, the conversations list appears empty and then suddenly populates the conversation list.

### 👟 Reproduction steps

1. Login into the [application](https://app.docsgpt.cloud/).
2. Observe the chat list.

### 👍 Expected behavior

https://github.com/user-attachments/assets/ed04b0b5-65d4-4b88-a08c-466c86281e3b

### 👎 Actual Behavior with Screenshots

https://github.com/user-attachments/assets/c215e689-7ff2-4bc3-94b7-6eefe155aca0

### 💻 Operating system

Linux

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 🔒 Did you set the correct environment variables in the right path? List the environment variable names (not values please!)

-

### 📃 Provide any additional context for the Bug.

-

### 📖 Relevant log output

```shell
-
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by JeevaRamanathan**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
 Bug fix / enhancement
- **Why was this change needed?** (You can also link to an open issue here)
There is no indication that the conversations are fetching in sidebar. Added a loader state and icon to indicate it's loading. Resolves #1342 
- **Other information**:
Without introducing separate variable I have just extended the conversations object. Please let me know if you suggest any other alternative approaches as well.

### CODE REVIEW

**Comment by dartpain** [comment]
Can you please provide some screenshots, thank yoU!

**Comment by tenokami** [comment]
@dartpain @JeevaRamanathan I'd suggest moving loader to the middle/center and all good 
image

**Comment by JeevaRamanathan** [comment]
Hi,
1. @dartpain I missed changing the preloading state, it's fixed now.
2. @tenokami I have moved it to center but noticed one thing, as `fetchConversation` is called while deleting conversation [here](https://github.com/arc53/DocsGPT/blob/88623754cfeba9a2d65d6fad44d0c2a13126d330/frontend/src/Navigation.tsx#L124#L132) to refresh the list, the loader appears in center. Your thoughts on this, is that ok?

https://github.com/user-attachments/assets/3b97d7af-2e51-4090-a9de-ece19bb32c99

**Comment by tenokami** [comment]
@JeevaRamanathan Frankly, that's not ideal...

**Comment by JeevaRamanathan** [comment]
@tenokami  I have conditionally stopped the loader if it's delete conversation. Does this align?


https://github.com/user-attachments/assets/f7d513f2-8b91-4ab0-8206-405e3c6b5556

**Comment by tenokami** [comment]
@JeevaRamanathan yes! thx

**Comment by JeevaRamanathan** [comment]
Hi @dartpain, it's ready now after the changes

**Comment by JeevaRamanathan** [comment]
Hi @ManishMadan2882, could you please have a look into this based on your time

**Review by ManishMadan2882 — APPROVED** [review]
LGTM, Thanks @JeevaRamanathan !

**Pull request merged**
