### PR TITLE
added delete index of vector store in faiss

### PR DESCRIPTION
**Pull request by shivanandmn**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
enhancement

- **Why was this change needed?** (You can also link to an open issue here)
#101

- **Other information**:

### CODE REVIEW

**Comment by shivanandmn** [comment]
@dartpain can you please look into my PR and merge it.

**Comment by dartpain** [comment]
Sorry for a long delay,
I appreciate this PR, but to close this isse we need to also create a new api endpoint that will be able to delete some parts. I suggest you create it in the application/api/user/routes.py

**Comment by shivanandmn** [comment]
@dartpain added new endpoint. Please do let me know your suggestions. I am new to contributing, and I am ready to accept any number of suggestions.

**Review by dartpain — APPROVED** [review]

**Comment by dartpain** [comment]
Thank you, @holopin-bot @shivanandmn

**Pull request merged**
