### PR TITLE
Enhancement: Updated Train other docs

### PR DESCRIPTION
**Pull request by 0xrahul6**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
docs updated
- **Why was this change needed?** (You can also link to an open issue here)
Docs enhancement
- **Other information**:

### CODE REVIEW

**Comment by dartpain** [comment]
Looks similar to #738  Please choose which PR to merge, I left comments on another one

**Comment by 0xrahul6** [comment]
> Looks similar to #738 Please choose which PR to merge, I left comments on another one

Merge this one

**Review by dartpain — APPROVED** [review]

**Comment by dartpain** [comment]
Thank you!

**Comment by dartpain** [comment]
@0xrahul6 we are finalising our order for shirts, we need an address to send your shirt to, please fill this in
https://airtable.com/appfkqFVjB0RpYCJh/shrXXM98xgRsbjO7s

**Comment by 0xrahul6** [comment]
> @0xrahul6 we are finalising our order for shirts, we need an address to send your shirt to, please fill this in https://airtable.com/appfkqFVjB0RpYCJh/shrXXM98xgRsbjO7s

Hi, alex I just filled out the form

**Pull request merged**
