### PR TITLE
Fix/issue#1014

### PR DESCRIPTION
**Pull request by utin-francis-peter**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
fix

- **Why was this change needed?** (You can also link to an open issue here)
To address the issues highlighted in issue#1014

- **Other information**:
closes: https://github.com/arc53/DocsGPT/issues/1014

### CODE REVIEW

**Review by ManishMadan2882 — CHANGES_REQUESTED** [review]
Thank you @utin-francis-peter  on the recent PR. I've reviewed the changes and have a couple of points of feedback:
* The gap between the conversation component and input field looks perfect on all screen widths.
* As the text increases in the input field
   i) The text touches the borders, please make sure that there is a little bit gap between the text and the borders
   ii) Border radius should get reduced on coming to next line in input
   
Screenshot from 2024-06-30 01-58-32

**Comment by utin-francis-peter** [comment]
> Thank you @utin-francis-peter on the recent PR. I've reviewed the changes and have a couple of points of feedback:
> 
> * The gap between the conversation component and input field looks perfect on all screen widths.
> * As the text increases in the input field
>   i) The text touches the borders, please make sure that there is a little bit gap between the text and the borders
>   ii) Border radius should get reduced on coming to next line in input
> 
> Screenshot from 2024-06-30 01-58-32

Hi, Manish. 

Thanks for the thorough testing. Also, my apologies for the late response. 

I'v e effected the requested fixes in the last commit. Thanks.

**Review by ManishMadan2882 — APPROVED** [review]
Thankyou @utin-francis-peter !

**Comment by utin-francis-peter** [comment]
> Thankyou @utin-francis-peter !

Always a pleasure, grand masti.

**Pull request merged**
