### PR TITLE
Vectorstore/lancedb

### PR DESCRIPTION
**Pull request by akashAD98**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
added lancedb as vector store 

- **Why was this change needed?** (You can also link to an open issue here)
 Lancedb is a serverless vector database for AI applications. Easily add long-term memory to your LLM apps

### CODE REVIEW

**Comment by akashAD98** [comment]
any chance to merge it

**Comment by akashAD98** [comment]
> * docs_init
Thanks for reply & review 
@siiddhantt  1.  done
2. I'm already importing settings . & there is no ant other configuration needed 
3. lancdb don't have support for delete methods as of now.when I check there langchain integration

**Comment by akashAD98** [comment]
@siiddhantt @dartpain

**Comment by dartpain** [comment]
My concern is how can we pass URI for example to make it work.
```
 uri = "data/sample-lancedb"
db = lancedb.connect(uri)
```

Check out the quickstart
https://lancedb.github.io/lancedb/basic/#installation

**Comment by akashAD98** [comment]
```
from langchain_community.vectorstores import LanceDB
from application.vectorstore.base import BaseVectorStore
from application.core.settings import settings

class LancedbStore(BaseVectorStore):
    def __init__(self, uri, embeddings_key):
        super().__init__()
        self.uri = uri
        self.embeddings_key = embeddings_key
        self.docsearch = None  
        
        # Initialize the embeddings using the provided key
        embeddings = self._get_embeddings(settings.EMBEDDINGS_NAME, self.embeddings_key)
        
        # Initialize LanceDB with the appropriate URI and embeddings
        self.docsearch = LanceDB(
            uri=self.uri,
            embedding=embeddings,
            api_key=settings.LANCE_API_KEY,  # Assuming API Key is managed in settings
            region=settings.LANCE_REGION    # Assuming Region is managed in settings
        )
    
    def search(self, query, k=5, **kwargs):
        # Perform a similarity search using LanceDB
        if self.docsearch:
            return self.docsearch.similarity_search(query=query, k=k, **kwargs)
        else:
            raise ValueError("LanceDB instance is not initialized.")
    
    def add_texts(self, texts, metadatas=None, ids=None, **kwargs):
        # Add texts to the LanceDB instance
        if self.docsearch:
            return self.docsearch.add_texts(texts, metadatas=metadatas, ids=ids, **kwargs)
        else:
            raise ValueError("LanceDB instance is not initialized.")
    
    def delete(self, ids=None, delete_all=False, filter=None, drop_columns=None, name=None, **kwargs):
        # Delete documents from the LanceDB instance
        if self.docsearch:
            self.docsearch.delete(ids=ids, delete_all=delete_all, filter=filter, drop_columns=drop_columns, name=name, **kwargs)
        else:
            raise ValueError("LanceDB instance is not initialized.")
    
    def save_local(self, *args, **kwargs):
        # Currently, it's just a placeholder as LanceDB operations are handled internally
        pass


```


can be done like this ? havnt tested but just approch @dartpain

**Comment by dartpain** [comment]
Yeah, I think this will solve most of the issues, sorry for a delay.

**Comment by akashAD98** [comment]
@dartpain can you please  add lancedb as vectordb ?  that would be very helpful as im looking for serverless vectordb so

**Comment by dartpain** [comment]
Yeah, Ill add it once I have a bit more capacity or someone from our team, I like the DB

**Comment by akashAD98** [comment]
thanks looking forward for this

**Comment by akashAD98** [comment]
@dartpain is there any plans for this to add support

**Comment by akashAD98** [comment]
@dartpain any update on this ?

**Pull request closed without merging**
