### PR TITLE
Make logo clickable

### PR DESCRIPTION
**Pull request by Piyush-Tilokani**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Solves issue #1221
Made the logo clickable to improve the overall user experience
- **Why was this change needed?** (You can also link to an open issue here)
It is a common practice to make the logo click redirect to an index page. as stated in #1221 

- **Other information**:
NA

@pabik please review and merge this PR

### CODE REVIEW

**Comment by dartpain** [comment]
Think the positioning is changed a bit now. Should have a bit more of a Gap as per the figma design.

Thank you!

**Comment by Piyush-Tilokani** [comment]
> Think the positioning is changed a bit now. Should have a bit more of a Gap as per the figma design.
> 
> Thank you!

Adjusted the positioning in the latest commit
The gap is now the same as it previously was

**Review by ManishMadan2882 — APPROVED** [review]
Thanks @Piyush-Tilokani !

**Comment by dartpain** [comment]
@holopin-bot @Piyush-Tilokani  Thank you!

**Comment by dartpain** [comment]
Hey @Piyush-Tilokani  please fill in this form if you are interested in a t-shirt
https://airtable.com/appikMaJwdHhC1SDP/pagoblCJ9W29wf6Hf/form

**Comment by Piyush-Tilokani** [comment]
@dartpain The size guide page doesn't seem to work 
It says "Access denied".

**Pull request merged**
