### PR TITLE
feat: add edit buttons

### LINKED ISSUE #1331: [FEATURE]: add “Edit on GitHub” buttons
### 🔖 Feature description

This feature is an Edit on GitHub button that appears at the bottom of a page on DocsGPT’s Doc site.

### 🎤 Why is this feature needed ?

In my experience with docs pages, having an edit button will make it easier for contributors to find the page that they need to refer to when making an update to a guide or what part of the documentation site.

### ✌️ How do you aim to achieve this?

I plan on asking @dartpain what has been used to build DocsGPT’s documentation site. From there, I will go to the tool’s website and find its tutorial on how to add edit buttons.

### 🔄️ Additional Information

I would for this to count towards Hacktoberfest 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by CBID2**
## Description
I added a Edit on GitHub button
- **Why was this change needed?** (You can also link to an open issue here)
By adding this feature, contributors can have an easier time make edits or find the page that needs the update before they make a Pull Request. 
Closes #1331 
- **Other information**:
This is my submission for Hacktoberfest

### CODE REVIEW

**Comment by CBID2** [comment]
Hey @dartpain. Can you review my PR please?

**Review by ManishMadan2882 — APPROVED** [review]
Thanks @CBID2

**Comment by dartpain** [comment]
@holopin-bot @sccalabr Thank you!

**Comment by dartpain** [comment]
@holopin-bot @CBID2 Thank you!

**Pull request merged**
