### PR TITLE
Add README.md in Assets Section

### PR DESCRIPTION
**Pull request by debnath003**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Added a README.md file in the Assets Section of the DocsGPT repository

- **Why was this change needed?** (You can also link to an open issue here)

To give an idea about the assets or swags one will get after successfully contributing a pull request

- **Other information**:

No

### CODE REVIEW

**Comment by debnath003** [comment]
@dartpain please review this PR and approve the PR! Waiting for the review!

**Comment by debnath003** [comment]
@dartpain please review this PR and approve the PR! Eagerly waiting for the review!

**Comment by debnath003** [comment]
@dartpain it has been a long time submitting this PR, please review it and merge it for hacktoberfest as not so much time is left! Waiting for your review! Thanks a lot!

**Comment by dartpain** [comment]
Please help me undestand why we have readme in the assets folder?

Thank you!

**Comment by dartpain** [comment]
Ahhh, I think you misunderstood assets folder is for things like pictures, basically to store them there.

But thank you.
My suggestion is to check out https://docs.docsgpt.co.uk/ and try to see what you can contribute there in docs/pages

**Pull request closed without merging**
