### PR TITLE
Feature: Add Search Bar to Navigation Component

### PR DESCRIPTION
**Pull request by adarsh-jha-dev**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This PR introduces a new feature to the Navigation component, adding a search bar that allows users to search for and filter conversations based on their names.

- **Why was this change needed?** (You can also link to an open issue here)
The addition of a search bar was needed to improve the user experience and make it easier for users to find specific conversations within the Navigation component.

- **Other information**:

- The search bar allows users to enter search queries and filters conversations accordingly.
- Conversations are now dynamically filtered based on the search query.
- The feature enhances usability, especially in cases where users have a large number of conversations.

### CODE REVIEW

**Comment by dartpain** [comment]
Thank you so much.
Just two things:
1. Can you send the screenshot so we can check how it looks
2. There is a build error


src/Navigation.tsx(173,33): error TS18047: 'conversations' is possibly 'null'.
--


<span>Error: Command "npm run build" exited with 2</span>

**Comment by adarsh-jha-dev** [comment]
> Thank you so much. Just two things:
> 
> 1. Can you send the screenshot so we can check how it looks
> 2. There is a build error
> 
> ## src/Navigation.tsx(173,33): error TS18047: 'conversations' is possibly 'null'.
> Error: Command "npm run build" exited with 2

I have tried to resolve that build error, could you please check that if the error is still there?

**Comment by dartpain** [comment]
Thank you, looks like its working, but desing wise its just on top of the page
Screenshot 2023-10-26 at 14 22 17

@tenokami maybe we can put search on top of the sidebar or something? how should we make it look?

**Comment by adarsh-jha-dev** [comment]
> Thank you, looks like its working, but desing wise its just on top of the page Screenshot 2023-10-26 at 14 22 17
> 
> @tenokami maybe we can put search on top of the sidebar or something? how should we make it look?

Thanks for considering, that was the problem i was unable to provide you the screenshot, i was worrying about the same, how should i make it look.

**Comment by dartpain** [comment]
There is an update available please sync with the latest version and checkout the design here to see how to integrate search
https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0-1&mode=design

eg
Screenshot 2023-10-31 at 00 43 01
Thank you!

**Comment by dartpain** [comment]
It failed to build,
here is the error trace


src/Navigation.tsx(260,11): error TS2657: JSX expressions must have one parent element.
--


<span>Error: Command "npm run build" exited with 2</span>

**Comment by adarsh-jha-dev** [comment]
@Alex , Really sorry for that build error, I will correct each and every
build error as well as make that front-end design by evening. Thank you.

**Comment by adarsh-jha-dev** [comment]
Hey @dartpain , I have made some changes , let me know if they are relevant or they need some modifications (i guess it should work now)

**Comment by dartpain** [comment]
There is another build error. here is the error trace:


 
--


<span>Error: Command "npm run build" exited with 2</span>

**Comment by adarsh-jha-dev** [comment]
> There is another build error. here is the error trace:
> 
> ##  
> Error: Command "npm run build" exited with 2

I think you missed to include the error trace

**Comment by adarsh-jha-dev** [comment]
> There is another build error. here is the error trace:
> 
> ##  
> Error: Command "npm run build" exited with 2

@dartpain , could you please give me the build error trace, I will fix it.

**Comment by dartpain** [comment]
Here is the trace


src/Navigation.tsx(291,11): error TS2657: JSX expressions must have one parent element.
src/Navigation.tsx(427,7): error TS1005: ')' expected.
Error: Command "npm run build" exited with 2
--


<span>Error: Command "npm run build" exited with 2</span>

**Comment by adarsh-jha-dev** [comment]
> Here is the trace
> 
> ## src/Navigation.tsx(291,11): error TS2657: JSX expressions must have one parent element.
> src/Navigation.tsx(427,7): error TS1005: ')' expected.
> Error: Command "npm run build" exited with 2
> Error: Command "npm run build" exited with 2

Hey @dartpain , could you please let me know if the build error is still there ?

**Comment by adarsh-jha-dev** [comment]
Have done some changes , let me know if the search is placed correctly now

**Comment by dartpain** [comment]
This is the way it looks now
Screenshot 2023-11-01 at 12 07 57


Also there are some left overs here:
Screenshot 2023-11-01 at 12 08 03


Please try to stick to the design as mentioned here
https://github.com/arc53/DocsGPT/pull/705#issuecomment-1786260635

Also it works as it is supposed to so functionality wise its good, its just the appearance

**Comment by dartpain** [comment]
You have this error

src/Navigation.tsx(182,11): error TS17014: JSX fragment has no corresponding closing tag.
src/Navigation.tsx(218,8): error TS1381: Unexpected token. Did you mean `{'}'}` or `&rbrace;`?
src/Navigation.tsx(474,7): error TS1003: Identifier expected.
src/Navigation.tsx(475,4): error TS1005: '}' expected.
src/Navigation.tsx(476,1): error TS1381: Unexpected token. Did you mean `{'}'}` or `&rbrace;`?
src/Navigation.tsx(477,1): error TS1005: '</' expected.
Error: Command "npm run build" exited with 2


<span>Error: Command "npm run build" exited with 2</span>

**Comment by dartpain** [comment]
You have this error here


src/Navigation.tsx(182,11): error TS17014: JSX fragment has no corresponding closing tag.
--
12:45:28.710 | src/Navigation.tsx(192,15): error TS1005: '}' expected.
12:45:28.710 | src/Navigation.tsx(218,8): error TS1381: Unexpected token. Did you mean `{'}'}` or `&rbrace;`?
12:45:28.710 | src/Navigation.tsx(476,7): error TS1003: Identifier expected.
12:45:28.710 | src/Navigation.tsx(477,4): error TS1005: '}' expected.
12:45:28.710 | src/Navigation.tsx(478,1): error TS1381: Unexpected token. Did you mean `{'}'}` or `&rbrace;`?
12:45:28.711 | src/Navigation.tsx(479,1): error TS1005: '</' expected.
12:45:28.731 | Error: Command "npm run build" exited with 2


Thank you,

Does it work locally for you?

**Comment by adarsh-jha-dev** [comment]
> You have this error here
> 
> ## src/Navigation.tsx(182,11): error TS17014: JSX fragment has no corresponding closing tag.
> 12:45:28.710 | src/Navigation.tsx(192,15): error TS1005: '}' expected. 12:45:28.710 | src/Navigation.tsx(218,8): error TS1381: Unexpected token. Did you mean `{'}'}` or `&rbrace;`? 12:45:28.710 | src/Navigation.tsx(476,7): error TS1003: Identifier expected. 12:45:28.710 | src/Navigation.tsx(477,4): error TS1005: '}' expected. 12:45:28.710 | src/Navigation.tsx(478,1): error TS1381: Unexpected token. Did you mean `{'}'}` or `&rbrace;`? 12:45:28.711 | src/Navigation.tsx(479,1): error TS1005: '</' expected. 12:45:28.731 | Error: Command "npm run build" exited with 2
> 
> Thank you,
> 
> Does it work locally for you?

Really sorry, wasn't working due to college exams, working on it now

**Comment by dartpain** [comment]
No worries, I just saw some commits and wanted to give some guidance.
Take you time, good luck with the exams!

**Pull request closed without merging**
