### PR TITLE
Dhruvkadam22 patch 4

### PR DESCRIPTION
**Pull request by DHRUVKADAM22**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

- **Why was this change needed?** (You can also link to an open issue here)

- **Other information**:

### CODE REVIEW

**Comment by dartpain** [comment]
Hi, thank you for much for this guide its quite useful, can we move it to
docs/pages/Deploying/Quickstart.md
Please

**Comment by DHRUVKADAM22** [comment]
> Hi, thank you for much for this guide its quite useful, can we move it to docs/pages/Deploying/Quickstart.md Please

So should I close this PR

**Comment by DHRUVKADAM22** [comment]
If everything is ok then please merge it .

**Comment by dartpain** [comment]
I think I commented on similar pr from you https://github.com/arc53/DocsGPT/pull/580

**Comment by dartpain** [comment]
Closing as #580  is merged

**Pull request closed without merging**
