### PR TITLE
Issue fix broken header in mobile viewports.

### PR DESCRIPTION
**Pull request by ParthMakode**
Fixed this by using z-index on navbar and list elements and also modified the copy, like and dislike button by using flexbox

- **What kind of change does this PR introduce?** 
- Bug Fix Issues of #618 

- **Why was this change needed?** (You can also link to an open issue here)
- The code had unnecessary relative and absolute tags. optimized those parts. Especially caused problems in mobile viewport.

The demo of the working of the fix is 
https://github.com/arc53/DocsGPT/assets/85568235/f605af29-3de1-48f7-ade3-592900bce601 +

### CODE REVIEW

**Comment by ParthMakode** [comment]
Can somebody please review this pull request?

**Comment by ParthMakode** [comment]
the second commit is because of conflicts. I resolved the conflicts .

**Comment by ParthMakode** [comment]
Hi @tenokami, 
can you review my pull request ?

**Comment by tenokami** [comment]
@ParthMakode I checked on the preview. Don't see the issue happening. 

Still @dartpain Should approve this PR

**Comment by ParthMakode** [comment]
Sure 😄

**Comment by dartpain** [comment]
Thank you so much for a PR, but it looks like this issue was fixed here
https://github.com/arc53/DocsGPT/pull/638

Please check if it still persists in the latest version. 
Unforunaltely i had to prioritise #638 as the user submitted the issue and indicated that they will work on it.
Thank you for your enthusiasm!

**Pull request closed without merging**
