### PR TITLE
Azure support #199

### PR DESCRIPTION
**Pull request by larinam**
A bit dirty commit, but I had a very aggressive formatting rule.
In the app.py the meaningful changes are lines 241-249.
Please review the other files thoroughly.

### CODE REVIEW

**Comment by warlockdn** [comment]
I think OPENAI_API_TYPE is missing in .env-template. Is it correct ?

**Comment by warlockdn** [comment]
I tried this today. Not really able to create embeddings or upload files as well

**Comment by larinam** [comment]
> I tried this today. Not really able to create embeddings or upload files as well

Hello, thank you for your feedback. 

I validated it works, following the existing deployment recommendation you can find here:
https://github.com/arc53/docsgpt/wiki/How-to-train-on-other-documentation.

Could you clarify your feedback? Maybe attach screenshots?

**Comment by dartpain** [comment]
Nice commit, ill change it a bit and will merge

**Comment by dartpain** [comment]
I think we can utilise LLM_NAME to identify that its openai

**Comment by larinam** [comment]
Just let me know if I can fix something to have the PR accepted and merged.

**Comment by larinam** [comment]
> I keep getting this error
> 
> Exception has occurred: ValidationError (note: full exception trace is shown but execution is paused at: _run_module_as_main) 1 validation error for OpenAIEmbeddings model extra fields not permitted (type=value_error.extra)
> 
> what do you think might be the issue here?
> 
> essentially fails here **scripts/parser/open_ai_func.py** - line 54 openai_embeddings = OpenAIEmbeddings(model=os.environ.get("AZURE_EMBEDDINGS_DEPLOYMENT_NAME"))

Could you provide the full stack trace, your .env file content, or all environment variables?

**Comment by warlockdn** [comment]
[nltk_data] Error loading punkt: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:997)>
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify
[nltk_data]     failed: unable to get local issuer certificate
[nltk_data]     (_ssl.c:997)>
input_files
[]
Grouping small documents
Separating large documents
Number of Tokens = 27,911
Approx Cost = $0.01
Price Okay? (Y/N) 
Y
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /DocsGPT-Azure/scripts/ingest.py:99 in ingest  │
│                                                                                                  │
│    96 │   │   folder_names.append(folder_name)                                                   │
│    97 │                                                                                          │
│    98 │   for directory, folder_name in zip(dir, folder_names):                                  │
│ ❱  99 │   │   process_one_docs(directory, folder_name)                                           │
│   100                                                                                            │
│   101                                                                                            │
│   102 @app.command()                                                                             │
│      ----------------------------------------------------------------------------                │
│ │           folder_name = 'inputs'                                                             │ │
│ │                  tqdm = <class 'tqdm.std.tqdm'>                                              │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /DocsGPT-Azure/pydantic/main.py:342 in         │
│ pydantic.main.BaseModel.__init__                                                                 │
│                                                                                                  │
│ [Errno 2] No such file or directory:                                                             │
│ '/DocsGPT-Azure/pydantic/main.py'              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValidationError: 1 validation error for OpenAIEmbeddings
model
  extra fields not permitted (type=value_error.extra)

**Comment by larinam** [comment]
Hi @warlockdn,

I apologise, but the information you provide is not helpful in debugging the problem you have. Do you have an Azure subscription with the approved OpenAI model usage and all the needed models created in the Azure environment?

**Comment by larinam** [comment]
Hi @dartpain , do you think some improvements are necessary here before this change can be merged? 
Could you let me know your feedback so I could fix it or accept the change so that I could work on further improvements? :)

**Comment by dartpain** [comment]
I had an extremely busy week...
Im very sorry Anton, you did provide amazing commit, just checked it all. I did think initially that the correct way to check would be via llm_name

could we maybe only add a small comment in .env_sample to show that those env variables are for OpenAI model

**Review by dartpain — APPROVED** [review]

**Comment by dartpain** [comment]
Done ive put the comment in there, Thank you!

**Comment by larinam** [comment]
Awesome! Thanks!

**Pull request merged**
