### PR TITLE
Support Anthropic, Palm, Huggingface, Ollama, TogetherAI, Replicate, etc.

### PR DESCRIPTION
**Pull request by krrishdholakia**
Hey @larinam @dartpain, 

Following @dartpain's feedback on this PR - https://github.com/arc53/DocsGPT/pull/394. 

I thought it might be easier if we just let the user use our cli tool to switch models without needing to make code changes to DocsGPT.

My PR shows users how to call their LLM providers (bedrock, togetherai, huggingface tgi, replicate, ai21, cohere, ai21 etc.) by pointing your openai base to a [local proxy](https://docs.litellm.ai/docs/proxy_server) they can use for experimentation.

Here's the suggested update to the ReadMe: 

# Use Anthropic,Huggingface,Palm,Ollama, etc.[Full List](https://docs.litellm.ai/docs/providers)

## Create OpenAI-proxy
We'll use [LiteLLM](https://docs.litellm.ai/docs/) to create an OpenAI-compatible endpoint, that translates OpenAI calls to any of the [supported providers](https://docs.litellm.ai/docs/providers).

```python
pip install litellm
```
```python
$ litellm --model ollama/codellama

#INFO: Ollama running on http://0.0.0.0:8000
```

[Docs](https://docs.litellm.ai/docs/proxy_server)

## Update DocsGPT
In your .env set the openai endpoint to your local server. 

```
OPENAI_ENDPOINT=http://0.0.0.0:8000
OPENAI_API_KEY=my-fake-key
```

### CODE REVIEW

**Comment by larinam** [comment]
@krrishdholakia 
1. Please have documentation and code changes as one PR to understand the relationship better.

**Comment by krrishdholakia** [comment]
Hey @larinam there are no code changes - it's just a doc update

**Comment by larinam** [comment]
> Hey @larinam there are no code changes - it's just a doc update

Of course, I mentioned the code change PR
https://github.com/arc53/DocsGPT/pull/394

**Comment by dartpain** [comment]
Its a good idea guys, we probably need a guide in our docs to make sure people can figure out how to make it work.
Somewhere here https://docs.docsgpt.co.uk/Guides/How-to-use-different-LLM

**Comment by larinam** [comment]
No activity.

**Pull request closed without merging**
