### PR TITLE
fix: virtual environment setup typo

### PR DESCRIPTION
**Pull request by Ayushpanditmoto**
typo fixing

Screenshot_1

### CODE REVIEW

**Review by larinam — CHANGES_REQUESTED** [review]
I see the following in the documentation. Maybe the previous section requires fixing, not this, Windows one?
Screenshot 2023-10-24 at 17 23 02

**Comment by Ayushpanditmoto** [comment]
@larinam  is this fine now ??

**Comment by Ayushpanditmoto** [comment]
i just made change for different command for different terminal commands

**Review by larinam — CHANGES_REQUESTED** [review]
I honestly think we don't need to extend this section of documentation. It should be basic knowledge of operating systems and Python/python environment documentation.
https://docs.python.org/3/tutorial/venv.html#creating-virtual-environments

If you want to help, please fix the problem in line 135 and that is it. And replace the link in line 129 with the one I shared above.

**Comment by larinam** [comment]
Unnecessary change.

**Pull request closed without merging**
