### PR TITLE
Cache local model to reduce memory usage and delays

### PR DESCRIPTION
**Pull request by starkgate**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Store the LLM after creation, for future use. This is especially necessary for local LLMs. Previously the LLM was recreated for each request, which caused long delays and doubled the GPU memory consumption.

- **Why was this change needed?** (You can also link to an open issue here)

Fixes https://github.com/arc53/DocsGPT/issues/945

- **Other information**:

### CODE REVIEW

**Comment by dartpain** [comment]
Sorry for a delay on this PR. Really appreciate it!
Main reason is because its a relative large conceptual change.
Personally I think there should be no LLM inference on our API container. Ideally it should be a separate one.
One kind of inference that I think is ok for the time being is embeddings, but it also causes issues with memory, I had multiple issues because of it on our production servers, so I moved embedding creation to a singleton instead of classic flask cache. 

[PR for embeddings](https://github.com/arc53/DocsGPT/pull/996)

Think both cache and singleton patterns are good, but I would prefer singleton pattern due to its more simplistic nature. Maybe because Im more used to it too.

Is there any advantage or disadvantage to either one that you see?

**Comment by starkgate** [comment]
> Sorry for a delay on this PR. Really appreciate it! Main reason is because its a relative large conceptual change. Personally I think there should be no LLM inference on our API container. Ideally it should be a separate one. One kind of inference that I think is ok for the time being is embeddings, but it also causes issues with memory, I had multiple issues because of it on our production servers, so I moved embedding creation to a singleton instead of classic flask cache.
> 
> [PR for embeddings](https://github.com/arc53/DocsGPT/pull/996)
> 
> Think both cache and singleton patterns are good, but I would prefer singleton pattern due to its more simplistic nature. Maybe because Im more used to it too.
> 
> Is there any advantage or disadvantage to either one that you see?

No worries on the delay. I chose the flask cache option since it seemed easier to implement: we need the cache/singleton to be accessible throughout the API, as a sort of global variable. Flask cache made this simple, just call the cache and you have your object. I wasn't sure how to do this cleanly with a singleton, admittedly I'm also not a Python expert, I could rework the PR to use a singleton instead of cache.

**Comment by dartpain** [comment]
Hey @starkgate Thank you so much for this PR, I do think we will go in favour of a singleton.
Also thank you so much for bringing it up as it brought up some other issues in our application. We definitely need to change things. If you can re-work it as a singleton - would be amazing!

**Comment by starkgate** [comment]
> Hey @starkgate Thank you so much for this PR, I do think we will go in favour of a singleton. Also thank you so much for bringing it up as it brought up some other issues in our application. We definitely need to change things. If you can re-work it as a singleton - would be amazing!

I'm glad to hear it helped!

**Pull request closed without merging**
