### PR TITLE
Feature n/lancedb

### PR DESCRIPTION
**Pull request by akashAD98**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Added support for lancedb as vectordb 

- **Other information**:
I have already created pr but there are a few things missing so I created a new pr 

also, I tested it & it's working now with Lancedb

image

### CODE REVIEW

**Comment by akashAD98** [comment]
@dartpain would be great if you could check & merge the pr .thank you

**Comment by akashAD98** [comment]
@ManishMadan2882 can you please check this pr?

**Comment by dartpain** [comment]
Hi, I seem to have an issue running it.

I added "`lancedb": LanceDBVectorStore, ` in `application/vectorstore/vector_creator.py` 
also set `VECTOR_STORE: str = "lancedb"`
Maybe there is something wrong with my setup? 
It does seem to be a good start for the solution imo

**Comment by akashAD98** [comment]
same changes i .did & i runned & its giving me output


image

**Comment by akashAD98** [comment]
also when i try to train  custom pdf/docs it's stuck every time. I tried with other vectord db also. same behavior across all. (maybe im doing wrong something )

image

**Comment by akashAD98** [comment]
@dartpain hi sir this pr is pending for 3 weeks.can you check it please?

**Comment by dartpain** [comment]
@akashAD98 
I really appreciate you PR, honestly, dont let my lack of response discourage you.
I think there is are some issues with it. Sometimes I try to fix them all myself, but only if I have time...

1. The way you init it, in some other uses it might overwrite the table name open
```
    def __init__(self, path: str = settings.LANCEDB_PATH,
                 table_name: str = settings.LANCEDB_TABLE_NAME,
                 embeddings_key: str = "embeddings"):
```
check out this file https://github.com/arc53/DocsGPT/blob/main/application/parser/open_ai_func.py

2. we dont filter by `source_id` as we should
3. This db is launched in an in memory mode, it will not be compatible with docker, since they need to share the files (worker and api)
4. Lets lazy import the dependency please

Most issues should be easy to fix.
Hardest one is the 3rd one, here you may need to re-think connection to db and init.
If im misunderstanding something about it, please correct me.

**Comment by AyushExel** [comment]
Hi @dartpain , I'm from LanceDB team. Just came across this PR. Could you please elaborate on point 3, as to why Lance wont work with docker? As for in-memory mode, LanceDB is persisted in storage rather than memory, so it doesn't need to load/create vector indices in memory. Let me know if you're seeing any weird behaviours

**Comment by akashAD98** [comment]
@dartpain any update on this

**Review by dartpain — APPROVED** [review]
LGTM, thank you so much, sorry for delays, had to test things

**Comment by dartpain** [comment]
@holopin-bot  @akashAD98  Thank you!

**Comment by dartpain** [comment]
@holopin-bot @akashAD98 Thank you!

**Comment by dartpain** [comment]
Hey @akashAD98 please fill in this form if you are interested in a t-shirt
https://airtable.com/appikMaJwdHhC1SDP/pagoblCJ9W29wf6Hf/form

**Pull request merged**
