### PR TITLE
Railway Deployment Guide Added

### PR DESCRIPTION
**Pull request by iamakhileshmishra**
- **What kind of change does this PR introduce?** 
- Added the Railway Deployment Guide as per the issue #461 assigned to me.

- **Why was this change needed?** 
- As it will help the user to deploy their DocsGPT to Railway Deploying platform and the Organizer of this Repository wanted a MarkDown Documentation for that as per #461 

- **Other information**:
- This is a contribution under Hacktoberfest please accept it under #Hacktoberfest-Accepted Tag so that I could get Hacktoberfest Recognition.

### CODE REVIEW

**Comment by dartpain** [comment]
Thank you so much for this PR, but it looks like you have some changes in package-lock.json that breaks compilation

**Comment by iamakhileshmishra** [comment]
> Thank you so much for this PR, but it looks like you have some changes in package-lock.json that breaks compilation

Could you please tell me in detail so that I could look on to this matter and resolve this asap

**Comment by iamakhileshmishra** [comment]
@dartpain I guess now all the checks are passed and it just require your approval could you please check and let me know

**Comment by iamakhileshmishra** [comment]
> @dartpain I have solved the package-lock.json could you recheck the issue with your end

**Comment by dartpain** [comment]
Thank you! @holopin-bot @iamakhileshmishra

**Comment by dartpain** [comment]
@iamakhileshmishra we are finalising our order for shirts, we need an address to send your shirt to, please fill this in
https://airtable.com/appfkqFVjB0RpYCJh/shrXXM98xgRsbjO7s

**Comment by iamakhileshmishra** [comment]
Done :) I have submitted the form @dartpain

**Pull request merged**
