### PR TITLE
Make README accessible

### PR DESCRIPTION
**Pull request by mishmanners**
Add accessibility features to README file based on the top tips from GitHub: https://github.blog/2023-10-26-5-tips-for-making-your-github-profile-page-accessible/

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Add accessibility features to README file based on the top tips from GitHub: https://github.blog/2023-10-26-5-tips-for-making-your-github-profile-page-accessible/

- **Why was this change needed?** (You can also link to an open issue here)

The README on your GitHub profile acts like a front door to your work, skills, and professional self, so it’s important that everyone who visits your profile can read and understand it.

### CODE REVIEW

**Comment by dartpain** [comment]
Thank you so much for making this page more accessible but looks like we also remove a lot of content on the readme, can we leave the other content in please.

**Comment by mishmanners** [comment]
I haven't removed any content @dartpain, everything should be exactly the same; just added accessibility; nothing should actually look any different unless we dug into the code behind it. So at face value it should look the same 😉

**Comment by mishmanners** [comment]
Oh I see what's happened... that's on my end... let me fix 😄

**Comment by mishmanners** [comment]
@dartpain all fixed and ready to go :smile: :heart:

**Review by dartpain — APPROVED** [review]

**Comment by dartpain** [comment]
Thank you so much!
@holopin-bot @mishmanners

**Pull request merged**
