### PR TITLE
Solved / #1294

### LINKED ISSUE #1294: 🐛 Bug Report: Disable scrolling and Close popup box clicking on three dots
### 📜 Description

Scrolling should be disabled when Popup is opened and when Popup is opened it should be closed by click on three dots.

### 👟 Reproduction steps

1. Open chats > click on three dost > scroll (see issue in attached screen recording)
2. Click on three dots again (on opened popup) > click on three dots (it will not close popup)

### 👍 Expected behavior

Scrolling should be disabled and popup should close when again click on three dots.

### 👎 Actual Behavior with Screenshots

https://github.com/user-attachments/assets/a92041e4-2ff6-4645-9a1c-11e54ef8df61

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Firefox

### 🤖 What development environment are you experiencing this bug on?

Docker

### 🔒 Did you set the correct environment variables in the right path? List the environment variable names (not values please!)

_No response_

### 📃 Provide any additional context for the Bug.

_No response_

### 📖 Relevant log output

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ayaan-qadri**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
 1. Resolves #1294 
 2. Disabled scrolling when popup is opened
 3. Now you can close (when popup us open) popup by clicking on again three dots

- **Why was this change needed?** (You can also link to an open issue here)
Provide a better experience and remove unevenness in the UI.

- **Other information**:
      -

### CODE REVIEW

**Comment by ManishMadan2882** [comment]
@ayaan-qadri Just reviewed, feels like the scroll bar toggles on clicking the menu, which makes it look inconsistent.
Can you please try some workaround to improve this?
Thanks!

closed
open

**Comment by ayaan-qadri** [comment]
> Just reviewed, feels like the scroll bar toggles on clicking the menu, which makes it look inconsistent

@ManishMadan2882 , Do you want to remove the scrollbar when it's enabled, or am I misunderstanding?

**Comment by dartpain** [comment]
I thin Manish suggests not to remove scrollbar when its enabled, such that its visible

**Comment by ayaan-qadri** [comment]
> I thin Manish suggests not to remove scrollbar when its enabled, such that its visible

If this is the case, then it should be as it is now because when you pop up, we do not allow scrolling. If the scrollbar still appears, it suggests that the portion is scrollable, which it is not. let me know if you want that apperience.

**Comment by ayaan-qadri** [comment]
@ManishMadan2882, I have made changes as per your request, let me know further if there are any changes that should be made.

**Review by ManishMadan2882 — APPROVED** [review]
Perfect @ayaan-qadri , Thanks !

**Pull request merged**
