### PR TITLE
Fixed edit and resend issue

### PR DESCRIPTION
**Pull request by Niharika0104**
Fixes: #1260 
Added a new point which will update the queries array in the current conversation.
This will fix edit and resend issue.

### CODE REVIEW

**Comment by siiddhantt** [comment]
Hi @Niharika0104 thanks for contributing! 
Just tried it and noticed that whenever a query is edited the entire coversation below it resets as well. Could you take a look at that ? Try editing a middle query

**Comment by Niharika0104** [comment]
@siiddhantt Can you please check it now?

**Comment by siiddhantt** [comment]
hi @Niharika0104 much better thanks!
Just a minor UI change I could suggest as per the figma design
The background (in dark mode) and size of the textbox
Screenshot 2024-11-22 at 6 25 03 PM

**Comment by Niharika0104** [comment]
@siiddhantt 
image
is this fine now?

**Comment by Niharika0104** [comment]
image
@siiddhantt

**Review by dartpain — APPROVED** [review]

**Comment by dartpain** [comment]
Thank you!

**Pull request merged**
