### PR TITLE
Update About.tsx

### PR DESCRIPTION
**Pull request by aindree-2005**
Text decorations added

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This highlights DOCSGPT on About Page and makes links colourful
- **Why was this change needed?** (You can also link to an open issue here)
For beautification of text

- **Other information**:

### CODE REVIEW

**Comment by dartpain** [comment]
Got this error trace


src/About.tsx(54,35): error TS2322: Type '{ children: string; clasname: string; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLSpanElement>, HTMLSpanElement>'.
--


<span>Error: Command "npm run build" exited with 2</span>

**Comment by aindree-2005** [comment]
Thank you!! It was a spelling error on my part

**Comment by dartpain** [comment]
Also can you remove underline decoration-blue-200 decoration-dotted class that you have added please. 
The changes inside span are good. 
Thank you!

**Comment by aindree-2005** [comment]
@dartpain  done!

**Review by dartpain — APPROVED** [review]

**Comment by dartpain** [comment]
@holopin-bot @aindree-2005 Thank you

**Pull request merged**
