### PR TITLE
Fix "Sources" Feature doesn't look as intended

### PR DESCRIPTION
**Pull request by adityagupta19**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix: made the sources feature look more like the figma design.
- **Why was this change needed?** (You can also link to an open issue here)
[Issue](https://github.com/arc53/DocsGPT/issues/421)
- **Other information**:
- before: 
Screenshot 2023-10-07 131936
- after:
Screenshot 2023-10-07 132210

### CODE REVIEW

**Comment by dartpain** [comment]
You have sibmitted some of the changes inside  frontend/src/Hero.tsx can you please remove that and just submit changes in frontend/src/conversation/ConversationBubble.tsx

Thank you!

**Comment by adityagupta19** [comment]
> You have sibmitted some of the changes inside frontend/src/Hero.tsx can you please remove that and just submit changes in frontend/src/conversation/ConversationBubble.tsx
> 
> Thank you!

**Comment by adityagupta19** [comment]
> You have sibmitted some of the changes inside frontend/src/Hero.tsx can you please remove that and just submit changes in frontend/src/conversation/ConversationBubble.tsx
> 
> Thank you!

I have now reverted the changes in the frontend/src/Hero.tsx

**Comment by dartpain** [comment]
Thank you!

**Review by dartpain — APPROVED** [review]

**Pull request merged**
