### PR TITLE
[Code]:Setting Section UI

### LINKED ISSUE #664: 🚀 Feature: Add "Settings" Button to sidebar
### 🔖 Feature description

"Settings" Button to sidebar. When it's clicked, It opens a page within DocsGPT which will have a headline and 4 empty tabs (no content inside tabs at the moment):

For both light and dark themes

General, Prompts, Documents, Widgets.

image
image
image
image

Figma: 

https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0%3A1&mode=design&t=hodJdNH0wH8O0Tu6-1

### 🎤 Why is this feature needed ?

Adding a new page "Settings" with tabs will create a good place to put DocsGPT settings such as language select, theme, prompts, documents, widgets and more

### ✌️ How do you aim to achieve this?

By adding a new page "Settings" with tabs and then adding elements to these pages

### 🔄️ Additional Information

_No response_

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

### PR DESCRIPTION
**Pull request by SamsShow**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- UI ->
- [x]          General Section
- [x]          Prompt Section
- [x]          Documents Section
- [x]          Widgets Section

- **Why was this change needed?** (You can also link to an open issue here)
- fixes #664 

- **Other information**:
-  I've created the complete UI in Typescript only, here's the preview of the UI
[Preview](https://github.com/arc53/DocsGPT/assets/74039834/87d8400b-b211-4f8a-8ca6-ea70a700a2d1)

@tenokami @dartpain

### CODE REVIEW

**Comment by SamsShow** [comment]
@dartpain

**Review by dartpain — APPROVED** [review]

**Comment by SamsShow** [comment]
@dartpain it was fun working on the setting section i would like to work more on docsGpt with your team

**Comment by dartpain** [comment]
Yes you are. Thank you so much!

**Comment by SamsShow** [comment]
> Yes you are. Thank you so much!
Thank You, I've applied for the Hacktober T-shirt

**Pull request merged**
