### PR TITLE
Fixed the feedback issue

### PR DESCRIPTION
**Pull request by Niharika0104**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fixes - #1166

### CODE REVIEW

**Review by ManishMadan2882 — CHANGES_REQUESTED** [review]
Hi @Niharika0104 
There is an error, could you please resolve.
```
line 201
    {"_id": ObjectId(data["conversation_id"]), f"queries.{data["question_index"]}": {"$exists": True}},
                                                                ^^^^^^^^^^^^^^
SyntaxError: f-string: unmatched '['
```

**Comment by Niharika0104** [comment]
@ManishMadan2882 can you check it now?

**Review by ManishMadan2882 — CHANGES_REQUESTED** [review]
@Niharika0104 
Thanks for the update, I have few points:
* The feedback once submitted, is not getting deleted. Like I liked once, but need to remove my reaction.
* The feedback once submitted, removes the other option. Like if I liked once, the dislike button is not visible.
image

**Comment by Niharika0104** [comment]
> @Niharika0104 
> Thanks for the update, I have few points:
> * The feedback once submitted, is not getting deleted. Like I liked once, but need to remove my reaction.
> * The feedback once submitted, removes the other option. Like if I liked once, the dislike button is not visible.
> image
> 

I thought that once the feedback is given it shouldn't be taken again.. that's how it's happening in the chatGPT as well

**Comment by Niharika0104** [comment]
@ManishMadan2882 so how should we change this and we want to take feedback only once the issue desc says so...

**Comment by Niharika0104** [comment]
> If the user clicks on the reaction which they have already submitted, it should get removed from the DB.

so when I click submitted feedback, then that particular feedback should be deleted from the db and also we should show the like and unlike buttons too.. 
correct me if I'm wrong..

**Comment by ManishMadan2882** [comment]
> > If the user clicks on the reaction which they have already submitted, it should get removed from the DB.
> 
> so when I click submitted feedback, then that particular feedback should be deleted from the db and also we should show the like and unlike buttons too.. correct me if I'm wrong..

Yep @Niharika0104

**Comment by ManishMadan2882** [comment]
@Niharika0104 are you active on this PR?

**Comment by ManishMadan2882** [comment]
@Niharika0104 I think you have not pushed the changes.

**Comment by Niharika0104** [comment]
@ManishMadan2882 Can you please check it now?

**Review by ManishMadan2882 — APPROVED** [review]
@Niharika0104 LGTM, Thanks!

**Pull request merged**
