### PR TITLE
fix milvus issues

### PR DESCRIPTION
**Pull request by zc277584121**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix for milvus. 
1. Comma missing
image

2. argument `filter` is not in the `_docsearch.similarity_search()`, instead , we can use `expr` 

3. add dependency inrequirements.txt

### CODE REVIEW

**Comment by zc277584121** [comment]
Hi @dartpain , could you (or anyone) please take a review

**Comment by dartpain** [comment]
Good pr, thank you.
Can we remove milvius as a dependency please from requirements.txt, as we want to keep it lazy loaded.

**Comment by zc277584121** [comment]
@dartpain thank you, I have removed it , please review again

**Review by dartpain — APPROVED** [review]
Thank you!

**Comment by dartpain** [comment]
@holopin-bot @zc277584121 Thank you!

**Comment by dartpain** [comment]
Hey @zc277584121 please fill in this form if you are interested in a t-shirt
https://airtable.com/appikMaJwdHhC1SDP/pagoblCJ9W29wf6Hf/form

**Comment by zc277584121** [comment]
> Hey @zc277584121 please fill in this form if you are interested in a t-shirt请填写此表单，如果您对购买 T 恤感兴趣 https://airtable.com/appikMaJwdHhC1SDP/pagoblCJ9W29wf6Hf/form

thank you

**Pull request merged**
