### PR TITLE
Feat: enhance mobile responsiveness of hero page

### PR DESCRIPTION
**Pull request by varundhand**
- **What kind of change does this PR introduce?** 
- This PR introduces a new **feature** to improve the **mobile responsiveness** of the website. 

- **Why was this change needed?** 
- Fixes issue #682 
- Previously, users had to **scroll down** on **mobile** devices to access the input field on the _home page_. This change enhances the user experience by ensuring that the input field is immediately visible, eliminating the need for unnecessary scrolling.

- **Other information**:
- _Before:_
Screenshot 2023-10-24 at 6 46 15 PM

- _After:_

Screenshot 2023-10-24 at 6 21 32 PM

### CODE REVIEW

**Comment by varundhand** [comment]
@dartpain I have resolved the merge conflicts here. Sorry for the inconvenience.

**Comment by dartpain** [comment]
Good PR, but a few small note
Can you remove * eslint-disable react/no-unescaped-entities */
// eslint-disable-next-line @typescript-eslint/no-unused-vars on the top of the file please

**Comment by varundhand** [comment]
@dartpain I have removed the eslint disable comments. Ready for review :)

**Comment by varundhand** [comment]
I have fixed the build error now.

**Comment by dartpain** [comment]
Perfect! thank you!
Just one note use this to check if itsmobile:
import { useMediaQuery } from './hooks';
const { isMobile } = useMediaQuery();

**Comment by varundhand** [comment]
Done the required changes.

**Comment by dartpain** [comment]
Can you please sync with the main branch and resolve the conflict, once done, i will merge.

Thank you!

**Comment by varundhand** [comment]
@dartpain I have resolved the merge conflicts.

**Comment by dartpain** [comment]
In your commit there is a change on frontend/src/assets/checkmark.svg just remove it please so i can merge. As color is supposed to be green.

Thank you!

**Comment by varundhand** [comment]
yes @dartpain about that, I think there is some error with the staging of the file. It automatically made changes to that file and when I tried to stash it, nothing would happen. Anyways I ll make one more commit fixing that hopefully, it'll be fine then.

**Comment by varundhand** [comment]
I think the file is untracked thats why its causing errors. Although I have pushed new commits, you may check if its working now.

**Comment by dartpain** [comment]
Its still there, I suggest you create a new PR and i will merge quickly. You can also try syncing with master again please

**Comment by varundhand** [comment]
@dartpain new Pr #752

**Pull request closed without merging**
