### PR TITLE
Add Traditional Chinese(zhTW) locale

### PR DESCRIPTION
**Pull request by PeterDaveHello**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

	Add Traditional Chinese(zhTW) locale

- **Why was this change needed?** (You can also link to an open issue here)

	More language support, more users approach

- **Other information**:

	None

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@dartpain can you also help review this one? Thanks.

**Comment by ManishMadan2882** [comment]
Perfect @PeterDaveHello,
Requesting a minor change to follow the general convention for locale codes, like `zh-TW`.
This should allow the browsers to detect the language from browser settings.

**Comment by PeterDaveHello** [comment]
@ManishMadan2882 done :+1:

**Review by ManishMadan2882 — APPROVED** [review]
Thankyou @PeterDaveHello !

**Comment by dartpain** [comment]
Hey there is a build log issue

[20:05:35.939] Running build in Washington, D.C., USA (East) – iad1
[20:05:36.057] Cloning github.com/arc53/DocsGPT (Branch: Add-zhTW-locale, Commit: ed5db76)
[20:05:36.068] Skipping build cache, deployment was triggered without cache.
[20:05:37.170] Cloning completed: 1.109s
[20:05:37.522] Running "vercel build"
[20:05:37.984] Vercel CLI 36.0.0
[20:05:38.612] Installing dependencies...
[20:05:48.576] 
[20:05:48.577] > frontend@0.0.0 prepare
[20:05:48.577] > cd .. && husky install frontend/.husky
[20:05:48.577] 
[20:05:48.633] husky - Git hooks installed
[20:05:48.650] 
[20:05:48.650] added 841 packages in 10s
[20:05:48.651] 
[20:05:48.651] 301 packages are looking for funding
[20:05:48.651]   run `npm fund` for details
[20:05:48.677] Detected `package-lock.json` generated by npm 7+
[20:05:48.677] Running "npm run build"
[20:05:49.113] 
[20:05:49.113] > frontend@0.0.0 build
[20:05:49.113] > tsc && vite build
[20:05:49.113] 
[20:05:52.676] src/locale/i18n.ts(9,10): error TS1005: '=' expected.
[20:05:52.677] src/locale/i18n.ts(9,14): error TS1005: ';' expected.
[20:05:52.677] src/locale/i18n.ts(28,9): error TS1005: ',' expected.
[20:05:52.678] src/locale/i18n.ts(28,12): error TS1005: ',' expected.
[20:05:52.678] src/locale/i18n.ts(28,14): error TS1136: Property assignment expected.
[20:05:52.678] src/locale/i18n.ts(31,5): error TS1135: Argument expression expected.
[20:05:52.678] src/locale/i18n.ts(31,6): error TS1135: Argument expression expected.
[20:05:52.678] src/locale/i18n.ts(32,16): error TS1005: ',' expected.
[20:05:52.678] src/locale/i18n.ts(33,14): error TS1005: ',' expected.
[20:05:52.678] src/locale/i18n.ts(38,3): error TS1135: Argument expression expected.
[20:05:52.706] Error: Command "npm run build" exited with 2
[20:05:53.388]

**Comment by PeterDaveHello** [comment]
@ManishMadan2882 is there anything I should do here?

**Comment by ManishMadan2882** [comment]
Hi @PeterDaveHello 
There is an error in locale/i18n.ts, in the resources object try wrapping zh-TW as `"zh-TW"` in line 28
Thanks!

**Comment by dartpain** [comment]
src/locale/i18n.ts(9,10): error TS1005: '=' expected.
src/locale/i18n.ts(9,14): error TS1005: ';' expected.
Error: Command "npm run build" exited with 2

Still getting this error

**Comment by PeterDaveHello** [comment]
It looks like because the hyphen `-` in the import statement `import zh-TW from './zh-TW.json';` is not valid in JavaScript/TypeScript variable names.

Should we rename the variable like this:

```typescript
import zhTW from './zh-TW.json'; // Traditional Chinese
```

And then adjust the usage accordingly:

```typescript
"zh-TW": {
  translation: zhTW,
},
```

**Comment by ManishMadan2882** [comment]
@PeterDaveHello yes please, this should fix the syntax.

**Review by ManishMadan2882 — APPROVED** [review]
Thanks @PeterDaveHello

**Comment by dartpain** [comment]
@holopin-bot @PeterDaveHello  Thank you!

**Comment by dartpain** [comment]
Hey @PeterDaveHello  fill in this form if you are interested in a t-shirt
https://airtable.com/appikMaJwdHhC1SDP/pagoblCJ9W29wf6Hf/form

**Pull request merged**
