### PR TITLE
refactor: use MongoDB singleton for connection management

### LINKED ISSUE #1170: Re-structure mongodb connection
Re structure mongodb connection in the backend.
Make sure its done well in flask and we dont initiate multiple connections in multiple different files.
Please also suggest ideas with some justification.

Thank you!

### PR DESCRIPTION
**Pull request by kom-senapati**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Adds a file core/mongo_db.py for the singleton class of pymongo client which is used to get connections across all files and no extra connection is created.

- **Why was this change needed?** (You can also link to an open issue here)

Closes #1170

### CODE REVIEW

**Comment by dartpain** [comment]
Hey please check the imports and test the application.
Thank you

**Comment by kom-senapati** [comment]
I had tested it locally before doing PR

**Comment by dartpain** [comment]
It seems like tests are failing for it:
https://github.com/arc53/DocsGPT/actions/runs/11397141420/job/31712108327?pr=1335
```
______________________ ERROR collecting tests/test_app.py ______________________
ImportError while importing test module '/home/runner/work/DocsGPT/DocsGPT/tests/test_app.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.11.10/x[64](https://github.com/arc53/DocsGPT/actions/runs/11397141420/job/31712108327?pr=1335#step:5:65)/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_app.py:3: in <module>
    from application.api.answer.routes import answer
application/api/answer/routes.py:14: in <module>
    from core.mongo_db import MongoDB
E   ModuleNotFoundError: No module named 'core'
=============================== warnings summary ===============================
../../../../../opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/flask_restx/api.py:19
../../../../../opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/flask_restx/api.py:19
  /opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/flask_restx/api.py:19: DeprecationWarning: jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver. Please file a feature request (on referencing) if you are missing an API for the kind of customization you need.
    from jsonschema import RefResolver

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

---------- coverage: platform linux, python 3.11.10-final-0 ----------
Coverage XML written to file coverage.xml

=========================== short test summary info ============================
ERROR tests/llm/test_anthropic.py
ERROR tests/llm/test_openai.py
ERROR tests/llm/test_sagemaker.py
ERROR tests/test_app.py
!!!!!!!!!!!!!!!!!!! Interrupted: 4 errors during collection !!!!!!!!!!!!!!!!!!!!
======================== 2 warnings, 4 errors in 6.[82](https://github.com/arc53/DocsGPT/actions/runs/11397141420/job/31712108327?pr=1335#step:5:83)s =========================
```

**Review by dartpain — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
