### PR TITLE
Fix/retry-btn 

### PR DESCRIPTION
**Pull request by utin-francis-peter**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
fix/feature
- **Why was this change needed?** (You can also link to an open issue here)
Due to network or other reasons, a response generation may fail. With this fix/feature, a user can click on the "Retry" button to regenerate a failed response.
- **Other information**:
closes: https://github.com/arc53/DocsGPT/issues/978

### CODE REVIEW

**Comment by ManishMadan2882** [comment]
There are a few requested changes.
* The retry functionality should not hinder users from entering input into the input field.
* Please refer the [Figma design](https://www.figma.com/design/OXLtrl1EAy885to6S69554/DocsGPT?m=dev&node-id=2089-2993&t=MnM51wEjUiWYUMmO-1) for further details.

Thanks @utin-francis-peter !

**Comment by utin-francis-peter** [comment]
> There are a few requested changes.
> 
> * The retry functionality should not hinder users from entering input into the input field.
> * Please refer the [Figma design](https://www.figma.com/design/OXLtrl1EAy885to6S69554/DocsGPT?m=dev&node-id=2089-2993&t=MnM51wEjUiWYUMmO-1) for further details.
> 
> Thanks @utin-francis-peter !

Noted with thanks, Manish. 

I'll effect the requested changes now and revert accordingly.

**Comment by utin-francis-peter** [comment]
Hello, @ManishMadan2882 

-  retry functionality no longer hinder users from entering input into the input field. 
- when a new input is typed after a failed generation, the input is used to update the last (failed) query object. this behavior only happens when the last query failed to ensure all query objects remain useful and relevant.

**Comment by ManishMadan2882** [comment]
Perfect @utin-francis-peter, Thanks for the updates! 
There is a minor change:
* The button wrapper div has background color white, which obscures the bottom most Message bubble.
Screenshot from 2024-06-12 18-08-51
Thankyou.

**Comment by utin-francis-peter** [comment]
> Perfect @utin-francis-peter, Thanks for the updates! There is a minor change:
> 
>     * The button wrapper div has background color white, which obscures the bottom most Message bubble.
>       Screenshot from 2024-06-12 18-08-51
>       Thankyou.

Adjusted. 

Thanks, Manish.

**Comment by dartpain** [comment]
Thank you, congrats on you merged PR!

**Review by dartpain — APPROVED** [review]

**Comment by utin-francis-peter** [comment]
> Thank you, congrats on your merged PR!

Thanks for the insightful iterations, Sire Alex. 

Sire @ManishMadan2882, thanks for the thorough revisions. They were indeed helpful.

**Pull request merged**
