### PR TITLE
Parser for OpenAPI3(Swagger)

### LINKED ISSUE #26: OpenAPI3 (Swagger) parsing
OpenAPI3 (Swagger api) parsing of the json file would be extremely helpful as this is commonly published docs.

### PR DESCRIPTION
**Pull request by Exterminator11**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This PR introduces an enhancement to the existing functionality of the project, aiming to add support for parsing OpenAPI3(Swagger) files.

- **Why was this change needed?** (You can also link to an open issue here)
This PR fixes #26. 

- **Other information**:
The output is
   ```
  Base URL:http://petstore.swagger.io/, https://api.example.com/
  Path1: /pets
  description: None
  parameters: []
  methods: 
  get=A paged array of pets
  post=Null response
  Path2: /pets/{petId}
  description: None
  parameters: []
  methods: 
  get=Expected response to a valid request 
  ```

### CODE REVIEW

**Comment by dartpain** [comment]
Really like this PR, just one request, can you please add some tests for it. 

I will test and link to buik.py afterwards

**Comment by Exterminator11** [comment]
> Really like this PR, just one request, can you please add some tests for it.
> 
> I will test and link to buik.py afterwards

Thanks, will write some tests and get back!!

**Comment by dartpain** [comment]
Good PR, but there is a small issue with a test
==================================== ERRORS ====================================
________________ ERROR collecting tests/test_openapi3parser.py _________________
ImportError while importing test module '/home/runner/work/DocsGPT/DocsGPT/tests/test_openapi3parser.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_openapi3parser.py:2: in <module>
    from openapi_parser import parse
E   ModuleNotFoundError: No module named 'openapi_parser'
=============================== warnings summary ===============================
../../../../../opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/kombu/utils/compat.py:82
  /opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/kombu/utils/compat.py:82: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
    for ep in importlib_metadata.entry_points().get(namespace, [])

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

---------- coverage: platform linux, python 3.11.5-final-0 -----------
Coverage XML written to file coverage.xml

=========================== short test summary info ============================
ERROR tests/test_openapi3parser.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 1 warning, 1 error in 5.05s ==========================

**Comment by Exterminator11** [comment]
> Good PR, but there is a small issue with a test ==================================== ERRORS ==================================== ________________ ERROR collecting tests/test_openapi3parser.py _________________ ImportError while importing test module '/home/runner/work/DocsGPT/DocsGPT/tests/test_openapi3parser.py'. Hint: make sure your test modules/packages have valid Python names. Traceback: /opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/importlib/**init**.py:126: in import_module return _bootstrap._gcd_import(name[level:], package, level) tests/test_openapi3parser.py:2: in from openapi_parser import parse E ModuleNotFoundError: No module named 'openapi_parser' =============================== warnings summary =============================== ../../../../../opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/kombu/utils/compat.py:82 /opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/kombu/utils/compat.py:82: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select. for ep in importlib_metadata.entry_points().get(namespace, [])
> 
> -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
> 
> ---------- coverage: platform linux, python 3.11.5-final-0 ----------- Coverage XML written to file coverage.xml
> 
> =========================== short test summary info ============================ ERROR tests/test_openapi3parser.py !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!! ========================= 1 warning, 1 error in 5.05s ==========================


I guess this can be solved by a `pip install openapi3-parser`, should I add the library's name in the `requirements.txt` file?

**Comment by dartpain** [comment]
Just a small change to fix tests,
copy scripts/parser/file/openapi3_parser.py to application/parser/file/openapi3_parser.py
Also add new dependency to requirements file in the application/requirements.txt
Change the from scripts.parser.file.openapi3_parser import OpenAPI3Parser to 
from application.parser.file.openapi3_parser import OpenAPI3Parser

**Comment by dartpain** [comment]
line 6 from scripts.parser.file.base_parser import BaseParser please change to 
from application.parser.file.base_parser import BaseParser

**Review by dartpain — APPROVED** [review]

**Comment by dartpain** [comment]
Thank you so much, thats a great PR!
@holopin-bot @Exterminator11

**Comment by Exterminator11** [comment]
> Thank you so much, thats a great PR! @holopin-bot @Exterminator11

Couldn't have done it without the great community of DocsGPT❤️

**Pull request merged**
