### PR TITLE
Fixed Empty Spaces Passed in the Input Field

### PR DESCRIPTION
**Pull request by ArnabBCA**
Issue ID #382

The Input Field now handles Empty Spaces

### CODE REVIEW

**Comment by dartpain** [comment]
I think we still send the empty spaces if a user submits it as a request, maybe we should rather stop the send button from working if its empty. Somewhere around handleQuestion when it gets triggered in Conversation.tsx.

thank you!

**Comment by ArnabBCA** [comment]
> I think we still send the empty spaces if a user submits it as a request (it will basically send no empty spaces otherwise), maybe we should rather stop the send button from working if its empty. Somewhere around handleQuestion when it gets triggered in Conversation.tsx.
> 
> thank you!

Thank you for your feedback I will look into the code and make necessary changes.

**Comment by ArnabBCA** [comment]
> I think we still send the empty spaces if a user submits it as a request (it will basically send no empty spaces otherwise), maybe we should rather stop the send button from working if its empty. Somewhere around handleQuestion when it gets triggered in Conversation.tsx.
> 
> thank you!

I have moved the **_trim_** logic in the **handleQuestion** function as  you  told, now even if the user press enter or click button the handleQuestion will first check whether the question is empty or not then it will proceed else it will return . it will also not send any request to the backend also

**Review by dartpain — APPROVED** [review]

**Comment by dartpain** [comment]
@holopin-bot @ArnabBCA Thank you!

**Pull request merged**
