### PR TITLE
fixed homepage

### PR DESCRIPTION
**Pull request by ratishjain12**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
I have resolved the scripts folder and the card one kindly check and merge under hacktoberfest thank you :)
@dartpain 
- **Why was this change needed?** (You can also link to an open issue here)

- **Other information**:

### CODE REVIEW

**Comment by dartpain** [comment]
Hi, perfect, its 99% done,

Just fix the third block please
Screenshot 2023-10-05 at 23 28 17


To fix it just swap py-4 to p-6 on it please

**Comment by dartpain** [comment]
It will look like this 
Screenshot 2023-10-05 at 23 29 07
Right after

**Comment by ratishjain12** [comment]
Done I have made it p - 6

**Review by dartpain — APPROVED** [review]

**Comment by dartpain** [comment]
Perfect, thank you! @holopin-bot @ratishjain12

**Comment by ratishjain12** [comment]
> Perfect, thank you! @holopin-bot @ratishjain12

your welcom @dartpain ,
Hey if there is any other frontend related task or fix you have in your mind do let me know and I'll do it.

**Comment by dartpain** [comment]
@ratishjain12  we are finalising our order for shirts, we need an address to send your shirt to, please fill this in
https://airtable.com/appfkqFVjB0RpYCJh/shrXXM98xgRsbjO7s

**Comment by ratishjain12** [comment]
Sure @dartpain

**Pull request merged**
