### PR TITLE
Like/dislike button behavior changed

### LINKED ISSUE #500: 🚀 Feature: Like/dislike button behavior
### 🔖 Feature description

The button like or dislike once clicked, should behave exactly like in ChatGPT. Meaning it should stay visible and not hide

### 🎤 Why is this feature needed ?

To make it clear that the feedback has been provided for this response

### ✌️ How do you aim to achieve this?

By making the clicked button stay visible after it was clicked

### 🔄️ Additional Information

_No response_

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

### PR DESCRIPTION
**Pull request by Ankit-Matth**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fixes #500 
I've changed the behavior of the like/dislike buttons, that is, I've made DocsGPT's like/dislike buttons exactly like ChatGPT.
- **Why was this change needed?** (You can also link to an open issue here)
To make it clear that the feedback has been provided for a particular response.
- **Sample of output due to changes made by me**:
 
DocsGPT 🦖 - Personal - Microsoft_ Edge 2023-10-11 20-38-34

**Please merge my pull request with "hacktoberfest-accepted" tag.**

### CODE REVIEW

**Comment by dartpain** [comment]
This is behaviour after the change:
[Screen Recording 2023-10-11 at 21.58.27](https://s3-eu-west-2.amazonaws.com/arc53data/Screen-Recording-2023-10-11-at-21.56.50.mov)

This is behavoiur before the PR
[Screen Recording 2023-10-11 at 21.58.27](https://s3-eu-west-2.amazonaws.com/arc53data/Screen-Recording-2023-10-11-at-21.58.27.mov)

I think I undestand why you added it, maybe bacause you where using mock api, and we still didnt implement feeback there.

I appreciate you effort

**Comment by Ankit-Matth** [comment]
Hi @dartpain, you are correct that I am using mock API but in the issue #500, the behaviour of feedback buttons requested by @tenokami is exactly like ChatGPT. In chatGPT the copy button doesn't disappered so I made it visible after clicking the like / dislike button and also "like" button is represented by blue color (according to your figma design) , so I also changed the color of "like button" from purple to blue.

So, if you will merge my pull request, these two changes may be valuable and writing the code in this manner also works for the mock API.

**Comment by Ankit-Matth** [comment]
@dartpain, please clarify me about issue #500 and feel free to close this PR if it is not valuable.

**Comment by tenokami** [comment]
@Ankit-Matth I'm sorry, but where in figma the like button is blue?

There is issue with a revamping of these icons https://github.com/arc53/DocsGPT/issues/516

**Comment by Ankit-Matth** [comment]
Sorry @tenokami, I got a bit confused.
In figma design, the color of "like button" is not blue.

Now everything is resolved, please close this pull request because there is no need to merge it..

😔Sorry for this confusion.....😔

**Comment by dartpain** [comment]
No worrie @Ankit-Matth 
Thank you!

**Pull request closed without merging**
