### PR TITLE
Reusable  Attractive  Skeleton  Loader Component is  added  [Fixes #1181]

### LINKED ISSUE #1181: 🚀 Feature: Creating a reusable loader for all the tabs while fetching responses.
### 🔖 Feature description

1. Create a reusable skeleton component to handle asynchronous data(fetch)
2. Component can be integrated in Settings > Documents, Chatbots, Analytics, logs

### 🎤 Why is this feature needed ?

Improves UX:  Providing a skeleton loader helps maintain user engagement by showing a visual placeholder instead of a blank screen. This reduces perceived loading times and enhances the overall user experience.

### ✌️ How do you aim to achieve this?

The loader component will be designed to be highly flexible and customizable, enabling it to adapt to different shapes and structures (example: tables).

### 🔄️ Additional Information

Skeleton should match the design of the component in the [ConversationBubble](https://github.com/arc53/DocsGPT/blob/350c91889e13e058cd60b879703d478c9a2ea6cc/frontend/src/conversation/ConversationBubble.tsx#L108) component, which appears until the sources are streamed.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

### PR DESCRIPTION
**Pull request by prathamesh424**
Added Reuable Loader component [Fixes #1181 ]
 

https://github.com/user-attachments/assets/411607a0-e285-42d7-ba37-ed661bb217e2

https://github.com/user-attachments/assets/fa450e9a-4cae-4550-a733-1b97e76103ba

### CODE REVIEW

**Comment by prathamesh424** [comment]
for hacktoberfest and devfest

**Comment by dartpain** [comment]
Please make sure you use skeleton loader, similarly to what we have in the sources
CleanShot 2024-10-04 at 18 05 10@2x
CleanShot 2024-10-04 at 18 05 43

**Comment by prathamesh424** [comment]
### @dartpain  you can check now added  skeleton loader 


**call the function <SkeletonLoader count={4}   />   count represent the number of cards** 

dark theme : 
 
https://github.com/user-attachments/assets/2d4b925b-1d58-4ab5-bb6f-e1aea540e6f5


light theme: 

https://github.com/user-attachments/assets/640621e9-c383-45fd-ba35-2ac82e53e24e

**Comment by dartpain** [comment]
I think as part of the issue we need to use this component now in 
`Component can be integrated in Settings > Documents, Chatbots, Analytics, logs`

During the loading state as per the issue.

Thank you!

**Comment by prathamesh424** [comment]
### Updated the loading state and loader in the settings component : 

Screenshot 2024-10-06 110355
Screenshot 2024-10-06 110859
Screenshot 2024-10-06 110914
Screenshot 2024-10-06 111143
Screenshot 2024-10-06 105221

**Comment by dartpain** [comment]
Can we make this skeleton thing more responsive to the size of the window?
Such that if its a large window ( as we have in settings) we dont show multiple skeleton tabs, but one large for example.
Here is a good rundown:
https://www.nngroup.com/articles/skeleton-screens/

**Comment by prathamesh424** [comment]
**@dartpain** 
### check out   : now single  loader with responsive based on the window size : 

**small screen video**
https://github.com/user-attachments/assets/7453047b-7326-4f7a-ab82-8b5db4fde7b5

**large screen** 
Screenshot 2024-10-08 011254
Screenshot 2024-10-08 011142
Screenshot 2024-10-08 011121
Screenshot 2024-10-08 011112

**Comment by dartpain** [comment]
Hey @tenokami what do you think about those loader components?
Any comments / adjustements?

**Comment by tenokami** [comment]
@prathamesh424 

Hello! Thanks so much for your effort and contribution.

There are a few small adjustments that would help align the skeleton loaders more closely with our design system:

	1.	It would be great if you could revisit the color scheme for the skeletons to better match our UI across both themes.
	2.	For elements other than tables, consider tailoring the skeleton animations to more closely reflect the content they’re representing, such as mock skeleton graphs for analytics.
	3.	Taking a look at existing skeleton examples might provide some inspiration—especially in terms of positioning and structure.

**Comment by prathamesh424** [comment]
@dartpain  
Screenshot 2024-10-09 012736
Screenshot 2024-10-09 012728
Screenshot 2024-10-09 012721
Screenshot 2024-10-09 012711

**Comment by prathamesh424** [comment]
@dartpain  please check out I added custom loader for every component in teh settings

**Comment by prathamesh424** [comment]
@dartpain I want to apply for new issues so can you review it

**Comment by tenokami** [comment]
@prathamesh424 Can you upload videos to see how it looks animated?

**Comment by tenokami** [comment]
@prathamesh424 On the Chatbots tab we will have a table that will look like here https://github.com/arc53/DocsGPT/issues/1286

**Comment by prathamesh424** [comment]
preview : 

https://github.com/user-attachments/assets/007c6e7e-087e-4e61-8973-bf745328bb0b

**Comment by prathamesh424** [comment]
please add the **hactoberfest-accepted** tag  while merging

**Comment by prathamesh424** [comment]
@dartpain  please check out

**Comment by tenokami** [comment]
@dartpain Might be passable for the first version?

**Comment by prathamesh424** [comment]
@ManishMadan2882 can check out the pull request  ... under hacktoberfest and devfest

**Review by ManishMadan2882 — APPROVED** [review]
Hi @prathamesh424 
Thanks for an update, just reviewed the PR, have few points:
* The loader looks good and reasonably placed.
* Would be better to locate it in src/components instead of src/utils dir, please name the file as SkeletonLoader.tsx.
* Also, could you please sync the file with the upstream main, as there are merge conflicts.

**Comment by prathamesh424** [comment]
@ManishMadan2882 check out now I solved the conflicts

**Review by ManishMadan2882 — APPROVED** [review]
Looks good, Thanks @prathamesh424 !

**Comment by dartpain** [comment]
@holopin-bot @prathamesh424  Thank you!

**Comment by dartpain** [comment]
Hey @prathamesh424 please fill in this form if you are interested in a t-shirt
https://airtable.com/appikMaJwdHhC1SDP/pagoblCJ9W29wf6Hf/form

**Pull request merged**
