### PR TITLE
Update README.md -- Fixed #453

### LINKED ISSUE #453: 🐛 Bug Report: Adding code of conduct file link in Readme file !
### 📜 Description

code of conduct will be clearly visible if it would be in readme.md please assign this issue to me ! @larinam @

### 👟 Reproduction steps

Adding code of conduct file link in Readme file !

### 👍 Expected behavior

code of conduct file is not present in readme.md

### 👎 Actual Behavior with Screenshots

none

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

_No response_

### 🤖 What development environment are you experiencing this bug on?

Docker

### 🔒 Did you set the correct environment variables in the right path? List the environment variable names (not values please!)

_No response_

### 📃 Provide any additional context for the Bug.

_No response_

### 📖 Relevant log output

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mohitd404**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- ✅ Added code of conduct section to documentation.
- ✅ Added license section into the repository.
- ✅ Fixed some Typos.

- **Why was this change needed?** (You can also link to an open issue here)
- #453

### CODE REVIEW

**Comment by mohitd404** [comment]
@lucasventura99 please merge the PR !!

**Comment by larinam** [comment]
@mohitd404 , thank you for contributing!

1. Some changes are confusing and incorrect. Please make only changes in places you are 100% sure they make sense.
2. It already is not up-to-date and requires conflict resolution to proceed.

**Comment by mohitd404** [comment]
> @mohitd404 , thank you for contributing!
> 
> 1. Some changes are confusing and incorrect. Please make only changes in places you are 100% sure they make sense.
> 2. It already is not up-to-date and requires conflict resolution to proceed.

okay sir !

**Review by mohitd404 — COMMENTED** [review]
made the required changes please review it !

**Comment by larinam** [comment]
2.  Screenshot 2023-10-07 at 11 47 37

**Comment by mohitd404** [comment]
> 2. Screenshot 2023-10-07 at 11 47 37

@larinam now conflicts have been resolved, sir! please guide me if there is anything else I could do!

**Comment by dartpain** [comment]
@holopin-bot @mohitd404 Thank you!

**Review by dartpain — APPROVED** [review]

**Comment by mohitd404** [comment]
> @holopin-bot @mohitd404 Thank you!

Thank you for merging !

**Pull request merged**
