### PR TITLE
Update docs_parser.py

### PR DESCRIPTION
**Pull request by sOnU1002**
pip install PyPDF2 docx2txt pytesseract pdf2image

### CODE REVIEW

**Comment by dartpain** [comment]
Its a good place to do OCR on docx.
I think you have another PR open for OCR, can we consolidate it.
Also if you can link it to an issue - it would be much appreciated.

thank you!

**Comment by sOnU1002** [comment]
pip install pytesseract
 we need to runn this in enviroment but how can i add this i cant find requirment .txt

**Comment by dartpain** [comment]
Its in the application folder

**Comment by dartpain** [comment]
Are your other PR's active?
Maybe we can close some inactive ones?
https://github.com/arc53/DocsGPT/pulls?q=author%3AsOnU1002+

**Pull request closed without merging**
