### PR TITLE
feat: wrapper modal

### PR DESCRIPTION
**Pull request by RohittCodes**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
this pr introduces a wrapper modal, which will act as a base for every other modals. includes functionality to close the modal on a click outside the modal or an `ESC` key press.

- **Why was this change needed?** (You can also link to an open issue here)
fixes: #1231 

- **Other information**:

### CODE REVIEW

**Review by ManishMadan2882 — CHANGES_REQUESTED** [review]
Thanks @RohittCodes 
Looks good, requesting one minor change to let the train button disabled for remote uploads as well, when the link field is empty
image

**Comment by RohittCodes** [comment]
@ManishMadan2882 should I try adding something to prevent the modal from closing while training any upload?

**Comment by ManishMadan2882** [comment]
@RohittCodes Yes, we should avoid closing of the modal while upload/train is in process, good catch!

**Review by ManishMadan2882 — APPROVED** [review]
LGTM, thanks @RohittCodes !

**Pull request merged**
