### PR TITLE
Feat : add copy button on code snippet

### PR DESCRIPTION
**Pull request by sossost**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
feature
- **Why was this change needed?** (You can also link to an open issue here)
#950 
- **Other information**:

### CODE REVIEW

**Comment by dartpain** [comment]
Hi @sossost 
Thank you so much for your PR.
There are a few edits that we need to make before we can merge
CleanShot 2024-05-17 at 11 20 02@2x

1. The new copy button should only be displayed on code blocks. Not other text blocks too.
2. The copy button should become visible on hover over the code block itself, not the whole message.

Appreciate your contribution!

**Comment by sossost** [comment]
@dartpain Oh my mistake. I'm fool Additional work has been done and committed.

**Comment by dartpain** [comment]
@sossost No worries at all!
Thank you so much!

**Review by dartpain — APPROVED** [review]

**Comment by sossost** [comment]
@dartpain Thank you too. have a nice day

**Pull request merged**
