### PR TITLE
Feature update: Enhanced viewport handling and scrollbar styling.

### PR DESCRIPTION
**Pull request by PentesterPriyanshu**
Added Firefox-compatible scrollbar styling  By default, Firefox uses its own scrollbar styling, which can look inconsistent compared to other browsers

- Feature update: Enhanced viewport handling and scrollbar styling.
Why was this change needed?
issue :#1379

Added fallback for vh where dvh is unsupported.
Improved dark mode scrollbar contrast.
Ensured Firefox compatibility with custom scrollbars.
Other information:

Enhances cross-browser support and dark mode UX. Non-breaking.

### CODE REVIEW

**Comment by PentesterPriyanshu** [comment]
@Manish Madan

**Review by ManishMadan2882 — COMMENTED** [review]
Hi @PentesterPriyanshu 
The design of the scrollbars in light and dark mode look different
image
Screenshot from 2024-10-26 02-47-56

**Comment by PentesterPriyanshu** [comment]
Screenshot from 2024-10-26 05-28-39
Screenshot from 2024-10-26 05-28-18
now both looks same

**Comment by PentesterPriyanshu** [comment]
@dartpain

**Review by ManishMadan2882 — COMMENTED** [review]
@PentesterPriyanshu There is no change in Firefox

**Comment by PentesterPriyanshu** [comment]
it is the best consistency we can achieve since firefox has limited features than webkit browsers @ManishMadan2882 merge this pull request or any otherthing you can suggest 
i have improved scrollbar lot and maintained consistency as i have look in chatgpt also has this much difference becaise firefox has limited features

**Comment by PentesterPriyanshu** [comment]
This is the best consistency we can achieve, as Firefox has fewer features than WebKit-based browsers. @ManishMadan2882, please merge this pull request, or suggest any improvements if needed. I’ve made significant improvements to the scrollbar and maintained consistency. I noticed that even ChatGPT shows similar differences, likely due to Firefox's limited feature set.

**Comment by ManishMadan2882** [comment]
Agree with you, Firefox has fewer customisation for scrollbar. 
There is an error in the index.css in your previous commit
image

To be honest, I don't think these changes will be required as there is no update in the scrollbar.
Thanks.

**Pull request closed without merging**
