### PR TITLE
Documentation error in "Hacktoberfest.md"

### PR DESCRIPTION
**Pull request by negativenagesh**
simple Documentation error in [Hacktober](https://github.com/arc53/DocsGPT/blob/main/HACKTOBERFEST.md) file

### CODE REVIEW

**Comment by dartpain** [comment]
I hope you try another PR in future.

I suggest you try a code or documentation PR.

**Comment by negativenagesh** [comment]
> I hope you try another PR in future.
> 
> I suggest you try a code or documentation PR. 

@dartpain 

I'm very new to open source, it's been two months, I'm hard coding and this is my first time registering for Hacktoberfest, 

If you would be kind enough to put this PR as a hacktoberfest accepted.. it will be very motivating and helpful for me..

Or you can suggest me or assign me something to contribute to Hacktoberfest...

Thank you..

**Comment by negativenagesh** [comment]
> > I hope you try another PR in future.
> > 
> > I suggest you try a code or documentation PR. 
> 
> @dartpain 
> 
> I'm very new to open source, it's been two months, I'm hard coding and this is my first time registering for Hacktoberfest, 
> 
> If you would be kind enough to put this PR as a hacktoberfest accepted.. it will be very motivating and helpful for me..
> 
> Or you can suggest me or assign me something to contribute to Hacktoberfest...
> 
> Thank you..

[]()



@dartpain 

This small help would motivate me a lot...

**Comment by negativenagesh** [comment]
> I hope you try another PR in future.
> 
> I suggest you try a code or documentation PR.

@dartpain 

## Please can you put this PR as approved or Hacktoberfest-accepted that would be very helpful and kind of you

**Comment by dartpain** [comment]
@holopin-bot @negativenagesh Thank you!

**Pull request merged**
