### PR TITLE
Fix: Minimise sidebar on nav item click on Mobile

### LINKED ISSUE #1226: 🚀 Feature: On mobile sidebar minimisation
### 🔖 Feature description

On mobile, side bar should minimise upon click (item selection, such as settings) or off click. 

### 🎤 Why is this feature needed ?

Better usability. 

### ✌️ How do you aim to achieve this?

Check if mobile dimensions and alter behaviour. 

### 🔄️ Additional Information

_No response_

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

### PR DESCRIPTION
**Pull request by shatanikmahanty**
Fixed #1226

### CODE REVIEW

**Review by ManishMadan2882 — CHANGES_REQUESTED** [review]
Hi @shatanikmahanty,
Could you please add this functionality to the conversation tiles present in the Sidebar as well.
Thankyou !

**Comment by shatanikmahanty** [comment]
> Hi @shatanikmahanty, Could you please add this functionality to the conversation tiles present in the Sidebar as well. Thankyou !

Hi @ManishMadan2882, thanks for your review! Have updated the functionality accordingly.

**Review by ManishMadan2882 — APPROVED** [review]
Thanks @shatanikmahanty !

**Comment by shatanikmahanty** [comment]
> Hey, there is a build issue. Try `npm run build` please
> 
> ```
> src/Navigation.tsx(307,44): error TS7006: Parameter 'doc' implicitly has an 'any' type.
> Error: Command "npm run build" exited with 2
> ```

Sure will check it out and update the PR

**Comment by shatanikmahanty** [comment]
@dartpain thanks for the guidance on how to understand the issue. I have added the required type for the parameter in the callback.

**Comment by dartpain** [comment]
@holopin-bot @shatanikmahanty  Thank you!

**Pull request merged**
