### PR TITLE
Master

### PR DESCRIPTION
**Pull request by DhruvKadam-git**
1. Error Handling: Added try-except blocks for file operations and network requests.

2. Logging Enhancements: Improved logging to capture more detailed information.

3. Code Refactoring: Created download_file and upload_index functions to avoid code repetition.

4. Configuration: Used constants for MIN_TOKENS, MAX_TOKENS, and RECURSION_DEPTH.

### CODE REVIEW

**Comment by DhruvKadam-git** [comment]
please review these and let me know if it is ok or not

**Review by ManishMadan2882 — APPROVED** [review]
Perfect @DhruvKadam-git , Thankyou!

**Comment by dartpain** [comment]
@holopin-bot @DhruvKadam-git  Thank you!

**Comment by dartpain** [comment]
Hey @DhruvKadam-git please fill in this form if you are interested in a t-shirt
https://airtable.com/appikMaJwdHhC1SDP/pagoblCJ9W29wf6Hf/form

**Pull request merged**
