### PR TITLE
rename celery.py

### PR DESCRIPTION
**Pull request by xucailiang**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
  Renamed the cellery.py file and related references

- **Why was this change needed?** (You can also link to an open issue here)
  I encountered an error when starting the project，most likely due to a circular import
image

- **Other information**:

### CODE REVIEW

**Comment by xucailiang** [comment]
for fix：[#992 ](https://github.com/arc53/DocsGPT/issues/992)

**Comment by dartpain** [comment]
Hi @xucailiang 
Thank you for your commit, can we fix tests for it so we can merge.

**Comment by xucailiang** [comment]
> Hi @xucailiang Thank you for your commit, can we fix tests for it so we can merge.

yes, i think you can merge after the authorization is completed。

**Comment by xucailiang** [comment]
> Hi @xucailiang Thank you for your commit, can we fix tests for it so we can merge.

I realized that there was a missing change in the test_cellery.py file that caused the execution of the testing task to fail. I have fixed it and submitted it. I apologize for my carelessness

**Comment by dartpain** [comment]
Thank you so much @xucailiang
Happy to have you!

**Pull request merged**
