### PR TITLE
Fixed Typos and minor issues in CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by AnkitaSikdar005**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
    Docs Update  
- **Why was this change needed?** (You can also link to an open issue here)
    To improve the readability and understanding of the CODE_OF_CONDUCT.md file for contributors.
- **Other information**:
- Added bullets and fixed minor issues.

### CODE REVIEW

**Comment by AnkitaSikdar005** [comment]
@dartpain Please merge this pull request.

**Comment by dartpain** [comment]
Thank you for your PR, but it looks like the whole CODE_OF_CONDUCT.md file was just deleted.

**Comment by AnkitaSikdar005** [comment]
@dartpain  Sorry, it happened by mistake. I have made another new pr with  correct changes So ,I am now closing this pr.
                    I deeply regret for the inconvenience caused.

**Comment by dartpain** [comment]
No worries, thank you!

**Pull request closed without merging**
