### PR TITLE
added the copy response feature

### PR DESCRIPTION
**Pull request by ManishMadan2882**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Adding a button as the provided design
- **Why was this change needed?** (You can also link to an open issue here)
Its an expected feature from applications generating huge text responses

### CODE REVIEW

**Comment by dartpain** [comment]
Hi, looks like its too close, Thank you!
Screenshot 2023-10-08 at 01 13 41

**Comment by ManishMadan2882** [comment]
@dartpain Hey, I have made some corrections after your feedback.

**Comment by tenokami** [comment]
@ManishMadan2882 

1. The distance between all icons should be the same. Currently the space between copy and like is bigger
2. The icon for copy doesn't look like in design. 
3. After it's clicked it should change to a checkmark like in design
4. Hover doesn't work like indicated in figma

**Comment by ManishMadan2882** [comment]
I have made the changes @tenokami, added the margin evenly, added the checkmark.

**Comment by dartpain** [comment]
@holopin-bot @ManishMadan2882 Thank you!

**Review by dartpain — APPROVED** [review]

**Comment by ManishMadan2882** [comment]
Thankyou @dartpain

**Comment by tenokami** [comment]
Great job!

**Comment by ManishMadan2882** [comment]
Thankyou @tenokami

**Pull request merged**
