### PR TITLE
Add Bedrock, Ollama, Claude2, Cohere, Replicate [100+ LLMs] - using LiteLLM 

### PR DESCRIPTION
**Pull request by ishaan-jaff**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Uses litellm https://github.com/BerriAI/litellm for llm completion calls 
Example
```python
from litellm import completion

## set ENV variables
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion(model="command-nightly", messages)

# anthropic call
response = completion(model="claude-instant-1", messages=messages)
```

- **Why was this change needed?** (You can also link to an open issue here)
Add support for more LLMs 
- **Other information**:

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
Most repos use us for their OpenAI calls so I stuck to that format, see example PR: https://github.com/KillianLucas/open-interpreter/pull/124

**Comment by ishaan-jaff** [comment]
@dartpain based on your feedback in the previous PR

**Comment by larinam** [comment]
Hello @ishaan-jaff ,

The PR is an in-place replacement of one library to another. No additional documentation is committed on using other LLMs.
I don't see value in this change. Could you explain or modify the PR accordingly, please?

**Comment by krrishdholakia** [comment]
Hey @larinam litellm lets you easily call LLM APIs as a drop-in replacement for the openai-python sdk. Here's our docs if that helps - https://docs.litellm.ai/docs/. 

Acknowledging the feedback that this PR is missing related information. Maybe we can add that here as well? @ishaan-jaff 

What's a good place to add it @larinam

**Comment by larinam** [comment]
@krrishdholakia , the documentation lives in /docs folder of the repository root. Please find the appropriate place there. Maybe you may find https://github.com/arc53/DocsGPT/tree/main/docs/pages/Guides subsection as the relevant one for the documentation.

**Comment by larinam** [comment]
Can't be accepted In the existing shape. Recommendations provided, no response from the contributor, closing.

**Pull request closed without merging**
