### PR TITLE
fix: Remove extra spaces in response

### PR DESCRIPTION
**Pull request by HeetVekariya**
## **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
-  **Bug Fix**

## **Why was this change needed?** (You can also link to an open issue here)
- Issue: #533 
- Remove the extra (leading) spaces from the response

### Changes made:
- Added ```const trimmedResponse = query.response.trim();``` to trim the response
- Return the trimmed response if ```trimmedResponse.length > 0```, else ```No answer found.```

<br>

### Files changed:
- **Conversation.tsx** (frontend/src/conversation/Conversation.tsx)

<br>

### Total changes: 2

### CODE REVIEW

**Comment by HeetVekariya** [comment]
**Note** : I am not able to run the project locally, so we have to check if changes are correct or not in the vercel-docs-gpt deployment.

**Comment by dartpain** [comment]
I appreciate this PR but looks like the issue is still there
Screenshot 2023-10-14 at 13 38 57
Try to maybe alter margins

**Comment by HeetVekariya** [comment]
- LOL, i found that the problem is in the css (items-center)

- With ```items-center```
image

- Without ```items-center```
image


- I hope it does not affect anything else
- Also i have removed my previous changes

**Comment by HeetVekariya** [comment]
- Removed ```px-2``` of the ```Source``` to make response and source align vertically.

**Comment by dartpain** [comment]
Looks good now, thank you! @holopin-bot @HeetVekariya

**Review by dartpain — APPROVED** [review]

**Comment by HeetVekariya** [comment]
@dartpain Thank you for merging.

**Pull request merged**
