### PR TITLE
Replacing About with a Help dropdown that has contact and documentati…

### PR DESCRIPTION
**Pull request by sccalabr**
Creating a dropdown that will replace about with email and documentation. Fixes https://github.com/arc53/DocsGPT/pull/1204

### CODE REVIEW

**Comment by dartpain** [comment]
Thank you so much I have a few comments:
1. About button should be replace with help, not a new button above
CleanShot 2024-10-04 at 10 25 18@2x
Also the icon is good.
2. Please re-use existing dropdown component

**Comment by dartpain** [comment]
Thank you so much!

There seems to be an error
```
src/Navigation.tsx(336,16): error TS2741: Property 'selectedValue' is missing in type '{ placeholder: string; contentSize: string; options: { label: string; value: string; }[]; onSelect: (selectedOption: any) => void; }' but required in type '{ options: string[] | { name: string; id: string; type: string; }[] | { label: string; value: string; }[] | { value: number; description: string; }[]; selectedValue: string | { label: string; value: string; } | { ...; } | { ...; } | null; ... 10 more ...; contentSize?: string | undefined; }'.
src/Navigation.tsx(340,28): error TS7006: Parameter 'selectedOption' implicitly has an 'any' type.
src/components/Dropdown.tsx(101,40): error TS2322: Type 'string | { label: string; value: string; } | { value: number; description: string; } | { name: string; id: string; type: string; }' is not assignable to type 'object'.
  Type 'string' is not assignable to type 'object'.
src/components/Dropdown.tsx(109,55): error TS2339: Property 'top' does not exist on type '{}'.
Error: Command "npm run build" exited with 2
```

Try to use `npm run build` before pushing

**Comment by dartpain** [comment]
Which directory are you running it from?
Make sure its frontend/
Also make sure you install npm dependencies there

**Comment by dartpain** [comment]
Alright lets make this dropdown simpler and round it up a bit.
1. It should give similar hover effect as other buttons on Nav and look similar to it in default state
CleanShot 2024-10-05 at 23 56 37@2x
2. Let make sure it start from the i part on the help button too.
3. Lets make sure it looks rounded on top.

If it makes your task easier you can make a simpler separate component for it.

**Comment by dartpain** [comment]
@tenokami can we please make a figma edit such that it's easier to understand what change is needed with the help button that opens up a few help options.

Thank you!

**Comment by tenokami** [comment]
@sccalabr 
image
image
https://www.figma.com/design/OXLtrl1EAy885to6S69554/DocsGPT?node-id=0-1&t=fTHDgdhPXkMx4XIj-1

**Comment by tenokami** [comment]
@sccalabr Like here but it should have a white background in both places if u can update

image

**Comment by ManishMadan2882** [comment]
@sccalabr This needs to be a separate component, don't reuse the Dropdown or ConversationTile component.
In terms of design, as mentioned by @tenokami check the [menu in ConversationTile.tsx](https://github.com/arc53/DocsGPT/blob/94a8c42311ea62229dbf4c6e2b7fbefd39bd13b0/frontend/src/conversation/ConversationTile.tsx#L163)

**Comment by tenokami** [comment]
> @sccalabr This needs to be a separate component, don't reuse the Dropdown or ConversationTile component.
> 
> In terms of design, as mentioned by @tenokami check the [menu in ConversationTile.tsx](https://github.com/arc53/DocsGPT/blob/94a8c42311ea62229dbf4c6e2b7fbefd39bd13b0/frontend/src/conversation/ConversationTile.tsx#L163)

Thank you. I'm not a developer

**Comment by ManishMadan2882** [comment]
@sccalabr please find the Envelope icon in the  [figma](https://www.figma.com/design/OXLtrl1EAy885to6S69554/DocsGPT?node-id=0-1&t=fTHDgdhPXkMx4XIj-1).

**Comment by dartpain** [comment]
Looks like there is a conflict with the main branch
CleanShot 2024-10-10 at 19 17 56@2x
Please sync with it

**Comment by ManishMadan2882** [comment]
@sccalabr Have few points:
* Try to make the hover effect cover the whole block as in the design
image
* The Help section needs little bit vertical padding (py-1) to make it consistent.
image

**Review by ManishMadan2882 — CHANGES_REQUESTED** [review]
Thanks for the update @sccalabr .
Could you please run `npm run lint-fix` and push once.
Looks good but there are certain linting errors.

**Review by ManishMadan2882 — APPROVED** [review]
LGTM @sccalabr 
Thanks!

**Comment by dartpain** [comment]
Hey @sccalabr as per design that section should look like this
CleanShot 2024-10-12 at 16 38 58@2x
Please check out our figma 
https://www.figma.com/design/OXLtrl1EAy885to6S69554/DocsGPT?node-id=867-534&node-type=frame&t=LIBlsvZCmEkEH3xn-0
We are almost there, I think we need to change positioning a little and inceease height to match other buttons

**Review by ManishMadan2882 — APPROVED** [review]
Thanks for the update @sccalabr !

**Comment by dartpain** [comment]
@holopin-bot @sccalabr  Thank you!

**Pull request merged**
