### PR TITLE
[feature] : The UI of the feedback icons has been changed.

### LINKED ISSUE #516: 🚀 Feature: Revamp icon effects
### 🔖 Feature description

Update how icons look when they are hovered and clicked.
The copy button when clicked should change to the checkmark for 3 seconds and then change back to copy icon

image

https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0%3A1&mode=design&t=bb8MENOYPjbHRqwx-1

### 🎤 Why is this feature needed ?

Currently it doesn't look/feel good

### ✌️ How do you aim to achieve this?

By updating the UI/UX

### 🔄️ Additional Information

_No response_

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

### PR DESCRIPTION
**Pull request by Ankit-Matth**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
 I've made an update to how the icons look when hovered and clicked. And I've also set the copy button to change to a checkmark for 3 seconds when clicked and then back to the copy icon.
- **Why was this change needed?** (You can also link to an open issue here)
Fixes #516 
- **Before changes made by me :**

https://github.com/arc53/DocsGPT/assets/146843890/ae904335-fb3c-464c-9fbb-892de31cb764

- **After  changes made by me :**

https://github.com/arc53/DocsGPT/assets/146843890/c4c5d8dc-7a68-4f21-af1f-261f2d1a25a0

Please merge my pull request under "Hacktoberfest-accepted".

### CODE REVIEW

**Comment by Ankit-Matth** [comment]
Hey @dartpain, please review and merge this PR.

**Comment by dartpain** [comment]
Thank you for the PR, it looks great but there are few minor changes we need to make. 
Basically try to stick to a new design as much as you can, but the buttons on hover should not have color, and after press should have color https://github.com/arc53/DocsGPT/issues/516

Thank you so much @Ankit-Matth !

**Comment by Ankit-Matth** [comment]
> Thank you for the PR, it looks great but there are few minor changes we need to make. Basically try to stick to a new design as much as you can, but the buttons on hover should not have color, and after press should have color #516
> 
> Thank you so much @Ankit-Matth !

Hey @dartpain, I have made the changes as per your requirement.

Please review it once..

**Comment by dartpain** [comment]
Thank you @Ankit-Matth, good PR!

**Review by dartpain — APPROVED** [review]

**Pull request merged**
