### PR TITLE
Feature: Add "Settings" Button to sidebar

### PR DESCRIPTION
**Pull request by SoumyadiptoPal**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature: Add "Settings" Button to sidebar
- **Why was this change needed?** (You can also link to an open issue here)
solves issue #664
- **Other information**:

https://github.com/arc53/DocsGPT/assets/119007659/da58313e-4671-4bb8-ac5e-ae8529366ba6

image

### CODE REVIEW

**Comment by SoumyadiptoPal** [comment]
@dartpain please review this pull request

**Comment by tenokami** [comment]
1. image
2. Inactive tabs in light theme should have this font color like in figma: 747474, and on hover only text font color changes to: 7D54D1
image

3. 
image

Should be like in figma:

image

https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0%3A1&mode=design&t=T4nxPNHoRqKVSe7a-1

4. I'd prefer if the gear icon for settings matched the one in figma
image

5. On mobile screens, let's not use horizontal scroll bar. And instead make the same way it is on YouTube
image

i've placed arrors next to the frame in figma
image
image

**Comment by SoumyadiptoPal** [comment]
@tenokami can you please review and kindly merge this PR as today is the last day of hacktoberfeast. I will open separate issue to address the minute changes if required.
image
image

**Comment by tenokami** [comment]
@SoumyadiptoPal Thanks you

@dartpain WIll merge it shortly.

I'm gonna make a separate issue with some adjustments

**Comment by tenokami** [comment]
@SoumyadiptoPal https://github.com/arc53/DocsGPT/issues/740

**Comment by SoumyadiptoPal** [comment]
> @SoumyadiptoPal #740

Thank you sir. I will start working on the new issue😊

**Comment by SoumyadiptoPal** [comment]
@dartpain please merge🫠🫠

**Review by dartpain — APPROVED** [review]

**Comment by dartpain** [comment]
Thank you so much!
Btw all PR that have been created before and including 31st count towords contributions by hacktoberfest even if merged 7 days after

**Pull request merged**
