### PR TITLE
Feature: Table redesign

### PR DESCRIPTION
**Pull request by AkashJana18**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Changed hover effect, added search bar in 2 pages and added button as per requirement.

- **Why was this change needed?** (You can also link to an open issue here)
Fixes: #1286 

- **Other information**:
image
image

### CODE REVIEW

**Review by ManishMadan2882 — CHANGES_REQUESTED** [review]
Hi @AkashJana18, 
Just reviewed, have few points:
* Make sure the UI matches the [figma](https://www.figma.com/design/OXLtrl1EAy885to6S69554/DocsGPT?node-id=3219-6540&t=uw4j0m5fVAegrC5h-4)
* The Add new button  triggers the [Upload modal](https://github.com/arc53/DocsGPT/blob/main/frontend/src/upload/Upload.tsx)
* Search bar filters documents depending on document name
Also try to sync with main as there some tab design related changes in this file from your previous PR.
Thanks!

**Comment by AkashJana18** [comment]
Hey @ManishMadan2882 the required changes are made can you please check it out.
Feel free to ask for more changes if required :)

**Review by ManishMadan2882 — CHANGES_REQUESTED** [review]
Hi @AkashJana18 
Have few points:
1. There is an app crash on creating a new API Key
2. When the modal opens on clicking the  New Document button, it partially covers the screen
image
3. For table re-design, please follow [figma](https://www.figma.com/design/OXLtrl1EAy885to6S69554/DocsGPT?node-id=2249-2763&t=0foG6FzXO0AzhH0r-4), but you can ignore pagination for now as it will need few endpoints.
4. Also, please sync your branch with upstream main, there are conflicts.
Thanks!

**Comment by dartpain** [comment]
Hey @AkashJana18 how is it going?

**Comment by AkashJana18** [comment]
@dartpain working on it PR will updated soon

**Comment by AkashJana18** [comment]
Hey @ManishMadan2882  I have made the required changes
1. Can you specify the kind of app crash on creating new key? 
2. Also can guide me regarding resolving conflict. Like do i need to keep the skeleton reloader or remove it?

**Comment by ManishMadan2882** [comment]
Hi @AkashJana18 
1. The app crashes on creating new api key
The error is logged in the console
`Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at APIKeys.tsx:93:20`
2. We need to keep every change in the main branch including the skeleton.
Thanks.

**Comment by AkashJana18** [comment]
Hey @ManishMadan2882 conflicts have been resolved.
Can you please check if the apikey error is resolved or not.
Thank you.

**Comment by ManishMadan2882** [comment]
Hey @AkashJana18 
Do you mind testing these changes before pushing or is there any issue you are facing during set up on your system?

Fails with `npm run dev`
```
[plugin:vite:react-babel] /home/manish/Documents/contributors/akash jana/DocsGPT/frontend/src/settings/APIKeys.tsx: Unexpected token, expected "," (57:6)
  60 |       });
/home/manish/Documents/contributors/akash jana/DocsGPT/frontend/src/settings/APIKeys.tsx:57:6
55 |            );
56 |          }
57 |        })
   |        ^
58 |        .catch((error) => {
59 |          console.error(error);
```

**Comment by AkashJana18** [comment]
@ManishMadan2882 how do i revert the changes made while resolving conflict. I think i made error while resolving conflict if you can revert the change in APIkeys.tsx i can fix it.
i resolved conflict from github itself (not from vscode).

**Comment by ManishMadan2882** [comment]
Follow [this](https://app.docsgpt.cloud/share/ba110311-a138-4310-b10b-082156d5d468)

**Review by ManishMadan2882 — APPROVED** [review]
Perfect, Thanks @AkashJana18

**Pull request merged**
