### PR TITLE
Updated workflow of Contributing.md

### PR DESCRIPTION
**Pull request by neha3423**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- This PR is a docs update. 

- **Why was this change needed?** (You can also link to an open issue here)
- I have added two more steps in the workflow, to give a clear instructions to contribute to this repo smoothly for new contributors.

### CODE REVIEW

**Comment by neha3423** [comment]
Review requested @arc53

**Comment by neha3423** [comment]
Please review @arc53 @dartpain  @tenokami

**Comment by neha3423** [comment]
Please review @arc53 @dartpain @tenokami

**Review by dartpain — APPROVED** [review]

**Comment by dartpain** [comment]
Thank you, sorry for delay
@holopin-bot @neha3423

**Pull request merged**
