### PR TITLE
Github remote loader

### PR DESCRIPTION
**Pull request by dartpain**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Remote github loader
- **Why was this change needed?** (You can also link to an open issue here)
To load code from github
- **Other information**:

### CODE REVIEW

**Comment by dartpain** [comment]
Very simple loader that scrapes github repos
CleanShot 2024-10-05 at 21 54 38@2x

**Review by pabik — APPROVED** [review]

**Comment by dartpain** [comment]
@holopin-bot @dartpain

**Comment by dartpain** [comment]
@holopin-bot @dartpain

**Comment by dartpain** [comment]
@holopin-bot @dartpain contributor2024

**Comment by dartpain** [comment]
@holopin-bot @dartpain contributor2024

**Pull request merged**
