### PR TITLE
fix upload

### LINKED ISSUE #1210: 🚀 Feature: Updated UI/UX for "Upload new document" modal
### 🔖 Feature description

https://www.figma.com/design/OXLtrl1EAy885to6S69554/DocsGPT?node-id=0-1&t=N50TV6CgjXioM0rQ-1

image
image

### 🎤 Why is this feature needed ?

Better UI/UX

### ✌️ How do you aim to achieve this?

Better UI/UX

### 🔄️ Additional Information

It might be optimal to work on this issue after https://github.com/arc53/DocsGPT/issues/1201 is completed because they share some similarities that can be reused.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

### PR DESCRIPTION
**Pull request by RohittCodes**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This PR updates the previous upload component with a modal for uploading with 2 buttons separately.

- **Why was this change needed?** (You can also link to an open issue here)
This change fixes #1210, by introducing certain components as required for the UI upgrade.

- **Other information**:
### video ref

https://github.com/user-attachments/assets/399e3fd1-fa54-4eb5-b4a1-61be88b0122a

### CODE REVIEW

**Review by ManishMadan2882 — CHANGES_REQUESTED** [review]
Hi @RohittCodes 
Overall, it looks great, but I noticed a minor change.
Could you please make sure that the colour code in the buttons match the [design](https://www.figma.com/design/OXLtrl1EAy885to6S69554/DocsGPT?node-id=4442-10486&t=IoK0U4bzKrwHJqfK-4)
Thank you!

**Comment by RohittCodes** [comment]
@ManishMadan2882 I've fixed the colors in the button as per the required design for the node you've shared, and updated the gap between train and back button as I forgot about that while the first commit. Can you've a look please?

**Comment by ManishMadan2882** [comment]
Hi @RohittCodes 
Thanks for an update, just reviewed.
Could you please update the colour code for the 'Please wait' text (in Progress) to white.

**Comment by RohittCodes** [comment]
@ManishMadan2882 updated!

**Review by ManishMadan2882 — APPROVED** [review]
Perfect @RohittCodes 
Thank you !

**Comment by dartpain** [comment]
@holopin-bot @RohittCodes  Thank you!

**Pull request merged**
