### PR TITLE
Update CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by debnath003**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Updated the CODE_OF_CONDUCT.md. Changed the wording so that it can be easy to understand for everyone contributing for the first time.

- **Why was this change needed?** (You can also link to an open issue here)

It will help anyone who will be contributing for the first time, to read the contributing guidelines and code of conduct in this particular repository.

- **Other information**:

No

### CODE REVIEW

**Comment by debnath003** [comment]
@dartpain please approve this PR and merge the PR! Awaiting your review!

**Comment by debnath003** [comment]
@dartpain please approve this PR and merge the PR! Awaiting your review!

**Comment by debnath003** [comment]
@dartpain please check the review and approve the PR!

**Comment by debnath003** [comment]
@dartpain please review the PR and approve it! It has been a long time!

**Comment by dartpain** [comment]
@debnath003 I appreciate you contribution, thank you.
Can you please give more information on the changes you made and why they are needed

**Comment by debnath003** [comment]
@dartpain I actually updated the code of the conduct markdown file; I changed the whole markdown text and converted it into a very lucid and easy to understandable text, so that the first-time contributors should not face any problems when contributing and maintaining the code of conduct in this repository.

**Comment by debnath003** [comment]
@dartpain please review my PR and approve the PR! Waiting for your review!

**Comment by debnath003** [comment]
@dartpain please review my PR and approve the PR! Waiting for your approval

**Comment by debnath003** [comment]
@dartpain please review the given PR and approve that, it will be really helpful going into the hacktoberfest! Thank you!

**Comment by debnath003** [comment]
@dartpain it has been a long time since you reviewed the PR, please review the PR again and merge the PR! Waiting for your review! Thank you!

**Comment by dartpain** [comment]
I appreciate your choice to contrubite to DocsGPT, thank you so much. But unforunately code of conduct is a template provided by GitHub and we want to keep using it as its been approved by them. If you want to change its please try doing it with github on global level
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project

Thank you!

**Pull request closed without merging**
