### PR TITLE
Fix: Fonts on Safari browser

### LINKED ISSUE #1223: 🐛 Bug Report: Safari wrong fonts
### 📜 Description

In desktop Safari wrong fonts are displayed.

### 👟 Reproduction steps

Open DocsGPT on desktop Safari. 

### 👍 Expected behavior

image

### 👎 Actual Behavior with Screenshots

image

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Safari

### 🤖 What development environment are you experiencing this bug on?

Docker

### 🔒 Did you set the correct environment variables in the right path? List the environment variable names (not values please!)

_No response_

### 📃 Provide any additional context for the Bug.

_No response_

### 📖 Relevant log output

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by shatanikmahanty**
- **What kind of change does this PR introduce?** 
Bug Fix

- **Why was this change needed?**
Fixes #1223

### CODE REVIEW

**Comment by shatanikmahanty** [comment]
@ManishMadan2882 can you check once you are free if this is fine?

**Comment by ManishMadan2882** [comment]
@shatanikmahanty I tested on Safari, there wasn't any difference.
Could you please check it once, just make sure that you test on Safari specifically.

**Review by ManishMadan2882 — APPROVED** [review]
Thanks @shatanikmahanty

**Comment by shatanikmahanty** [comment]
@dartpain can you please merge once you are free, thanks ❤️

**Pull request merged**
