### PR TITLE
fix: share button available in mobile view

### PR DESCRIPTION
**Pull request by JeevaRamanathan**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug Fix
- **Why was this change needed?** (You can also link to an open issue here)
Address #1227 
image
Along with the avatar it would be:
image

### CODE REVIEW

**Comment by siiddhantt** [comment]
hi! @JeevaRamanathan 
the profile icon is entirely missing
Screenshot 2024-10-04 at 11 46 48 PM
and needs to be aligned properly
Screenshot 2024-10-04 at 11 50 06 PM

**Comment by JeevaRamanathan** [comment]
Hi @siiddhantt, based on this https://github.com/arc53/DocsGPT/issues/1227#issuecomment-2393937935, Profile icon is not on the open source version, if the screenshot that you shared is tested locally by any chance. Could you please confirm?

**Comment by siiddhantt** [comment]
oh true it's not on the OSS version, just the positioning then so it's aligned properly. Thanks!

**Comment by JeevaRamanathan** [comment]
@dartpain, @ManishMadan2882 requesting your review on this

**Review by ManishMadan2882 — CHANGES_REQUESTED** [review]
@JeevaRamanathan 
In mobile screen the Share button in Navigation is overlapped by another share button in the Conversation component.
Could you please try to have Share button in any one of the components and sync your branch.
Thanks!

**Comment by JeevaRamanathan** [comment]
Sure, let me check

**Comment by JeevaRamanathan** [comment]
Oh yeah, thanks for highlighting @ManishMadan2882, as Share button is used in multiple components I created a separate `ShareButton` component and used `hidden md:block` in Conversation component. Is this approach fine?

**Comment by JeevaRamanathan** [comment]
Hi @ManishMadan2882 merge conflict resolved!

**Comment by JeevaRamanathan** [comment]
Hi @ManishMadan2882, would you mind looking into this changes in completing this PR

**Review by ManishMadan2882 — APPROVED** [review]

**Pull request merged**
