### PR TITLE
Add Llama2, AI21, Aleph Alpha, Palm, Cohere, TogetherAI, Huggingface, etc. streaming

### PR DESCRIPTION
**Pull request by krrishdholakia**
Hi @larinam @dartpain.

This PR adds support for Llama2, AI21, Aleph Alpha, Palm, Cohere, TogetherAI, Huggingface inference endpoints for *streaming* using LiteLLM (https://github.com/BerriAI/litellm).

In addition, we also enable easy A/B testing of new LLM models in production: 

https://docs.litellm.ai/docs/tutorials/ab_test_llms

Happy to add additional tests / update documentation, if the initial PR looks good to you.

### CODE REVIEW

**Comment by larinam** [comment]
Hey @krrishdholakia,

Thank you for this pull request. A couple of notes though.

1. Please enable GitHub actions for your fork https://github.com/krrishdholakia/DocsGPT. It will show you some shortcomings of this pull request.
2. Please review https://github.com/arc53/DocsGPT/blob/main/CONTRIBUTING.md and accompany your changes with the relevant tests.

**Comment by krrishdholakia** [comment]
Sounds good @larinam - will hope to have this done by tomorrow.

**Comment by larinam** [comment]
On the second point, please see my PR, section Testing to find out how to run unit tests.
https://github.com/arc53/DocsGPT/pull/322/files

On the first point, I suspect you access the old frontend served by the flask application. If you are running through the recommended way with docker-compose, the frontend should be available at address http://localhost:5173/

**Comment by larinam** [comment]
Hi @krrishdholakia , please either fix this PR or withdraw it.

**Comment by dartpain** [comment]
Im closing this PR as code is outdated, If you want to integrate and showcase litellm create concrete class with it in the /application/llm folder. 
its been never been easier to do it

**Pull request closed without merging**
