### PR TITLE
refactor: clean up settings file for better structure

### PR DESCRIPTION
**Pull request by siiddhantt**

### CODE REVIEW

**Review by ManishMadan2882 — CHANGES_REQUESTED** [review]
There is a slight change in `frontend/src/components/Dropdown.tsx` line:51.
Class `border-silver` is missing from button, can you please check that.

**Comment by siiddhantt** [comment]
> There is a slight change in `frontend/src/components/Dropdown.tsx` line:51. Class `border-silver` is missing from button, can you please check that.

I had removed it to match with the dropdown content's border. Added it again and fixed the mismatch

**Comment by ManishMadan2882** [comment]
> > There is a slight change in `frontend/src/components/Dropdown.tsx` line:51. Class `border-silver` is missing from button, can you please check that.
> 
> I had removed it to match with the dropdown content's border. Added it again and fixed the mismatch

**Comment by dartpain** [comment]
Hey @siiddhantt 
We have an issue on vercel. here is an error trace
```
src/settings/APIKeys.tsx(211,13): error TS2322: Type '{ className: string; placeholder: string; selectedValue: { label: string; value: string; } | null; onSelect: (selection: { label: string; value: string; }) => void; options: { label: string; value: string; }[]; }' is not assignable to type 'IntrinsicAttributes & { options: string[] | { name: string; id: string; type: string; }[] | { label: string; value: string; }[]; selectedValue: string | { label: string; value: string; } | null; ... 9 more ...; alignMidddle?: boolean | undefined; }'.
  Property 'className' does not exist on type 'IntrinsicAttributes & { options: string[] | { name: string; id: string; type: string; }[] | { label: string; value: string; }[]; selectedValue: string | { label: string; value: string; } | null; ... 9 more ...; alignMidddle?: boolean | undefined; }'.
Error: Command "npm run build" exited with 2
```

Otherwise im happy to merge

**Pull request merged**
