### PR TITLE
Integrated Milvus Vector DB into main

### PR DESCRIPTION
**Pull request by Jacksonxhx**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- Integration of Milvus Vector DB

- **Why was this change needed?** (You can also link to an open issue here)
- Provide a new DB choice

- **Other information**:

### CODE REVIEW

**Comment by Jacksonxhx** [comment]
Hi, I might an authorization to delpoy

**Comment by Jacksonxhx** [comment]
Hi, is there anyone who can help me with the Vercel deployment?

**Comment by zc277584121** [comment]
we need this feature, @dartpain could you please help to review it?

**Comment by dartpain** [comment]
So few comments on this PR,
1. I added filter parameter to search method
2. Lots of upgrades to make it all work
3. Dont use Milvus here as local file - its recommended to deploy it separately, as worker and backend containers will query it.

Finally to install in just add 
`langchain-milvus==0.1.4`
to your requirements txt file

**Review by dartpain — APPROVED** [review]

**Pull request merged**
