### PR TITLE
Update react-widget.md

### PR DESCRIPTION
**Pull request by shruti-sen2004**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
-> Docs Update
- **Why was this change needed?** (You can also link to an open issue here)
-> I have provided numbering instead of bullet points.
- **Other information**: No

### CODE REVIEW

**Comment by shruti-sen2004** [comment]
@dartpain Please review my changes.

**Comment by shruti-sen2004** [comment]
@dartpain Please review my changes.

**Comment by shruti-sen2004** [comment]
@dartpain Please review my changes and merge my pull request

**Review by dartpain — APPROVED** [review]

**Comment by shruti-sen2004** [comment]
Hello @dartpain , sorry for disturbing ...but I have seen few of my friends getting a special holopin badge for contributing to DocsGPT.  I have made 2 contributions but never got a badge. Is there any special criteria for the badge?

**Comment by dartpain** [comment]
@shruti-sen2004 So sorry, I must have forgotten,
@holopin-bot @shruti-sen2004 
Thank you so much!

**Comment by shruti-sen2004** [comment]
Its ok....Thanks a lot 😊

**Pull request merged**
