### PR TITLE
[FIX] Question is hidden under the question input box

### PR DESCRIPTION
**Pull request by staticGuru**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
      Bug fix- 
      Close- issues #474,
      Close- issues #418 

- **Why was this change needed?** (You can also link to an open issue here)
    - Actually, the chat conversation query UI missed some edge case design scenarios. So, I added some design properties.

- **Other information**:
   **Before Fix:**
Questions Hidden
     **After Fix:**
     
Bug fix

### CODE REVIEW

**Comment by staticGuru** [comment]
@dartpain 
I request you to merge my PRS.
Thanks

**Comment by dartpain** [comment]
Thank you so much, please check this out
Basically this this is how input box should go over the questions
Screenshot 2023-10-07 at 23 20 52

Current version
Screenshot 2023-10-07 at 23 22 19

@tenokami please check

**Comment by tenokami** [comment]
@staticGuru This has only partially fixed the issue. the messages should cut off slightly above the input field. You can use bard or chat gpt as reference if that would help

**Comment by staticGuru** [comment]
Yeah sure @tenokami 
I will check and fix these issues.

**Comment by dartpain** [comment]
@tenokami check this out, I think the input box is a bit too wide?

thank you @staticGuru

**Comment by tenokami** [comment]
@dartpain There was an issue for reducing the width of the input field. But I have a feeling this recording was taken on a small screen so that's why is looks big.

**Comment by tenokami** [comment]
I think this looks good @staticGuru Thank you

**Review by dartpain — APPROVED** [review]

**Comment by staticGuru** [comment]
Hi @dartpain
Thank you for accepting my pull requests and I'm happy to hear that you'd like to add the `hacktoberfest-accepted` label.

**Comment by tenokami** [comment]
@staticGuru Added the label

**Pull request merged**
