### PR TITLE
Enhancement: Improve API Endpoint Documentation

### PR DESCRIPTION
**Pull request by rahul0x00**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
docs
- **Why was this change needed?** (You can also link to an open issue here)

- **Other information**:

### CODE REVIEW

**Comment by rahul0x00** [comment]
Numbering the APIs looks better,should we do this?

**1. /api/answer1**

 it looks more better ig

**Review by dartpain — APPROVED** [review]
Good PR, Thank you!

**Comment by dartpain** [comment]
@rahul0x00  sorry, yes please push numbering, thank you for the suggestion

**Comment by rahul0x00** [comment]
Hi, @dartpain 
numbered the api's

**Comment by rahul0x00** [comment]
@dartpain  just a reminder

**Review by dartpain — APPROVED** [review]

**Pull request merged**
