### PR TITLE
Fix formatting of mobile retry button

### PR DESCRIPTION
**Pull request by ovindu-a**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

This PR changes the size of the retry button when on mobile and also hides the "Retry" text so the UI looks more viewable.

- **Why was this change needed?** (You can also link to an open issue here)

This was to fix issue #1230 where the retry button being too big in mobile view

- **Other information**:
image

Initial change makes it look like this. If this way of approaching is fine can edit the styles for it to make it look better.

### CODE REVIEW

**Comment by ManishMadan2882** [comment]
Hi @ovindu-a 
It would be better to have a small regenerate icon instead of the Copy button in case of error, think it will look better on other devices as well.

**Comment by dartpain** [comment]
Yep, that would be great, thank you!

**Comment by ovindu-a** [comment]
Will do.

**Comment by ovindu-a** [comment]
image

How does this look? @dartpain

**Comment by dartpain** [comment]
Think this looks great!

**Comment by ovindu-a** [comment]
@dartpain I have made the changes in the newest commit.

**Review by ManishMadan2882 — CHANGES_REQUESTED** [review]
Hi @ovindu-a 
In case of no error, there is an empty space because of hidden retry icon, would suggest to conditionally render.
image
Thanks!

**Comment by ovindu-a** [comment]
@ManishMadan2882 I have made the requested change, please let me know if this is alright

**Review by ManishMadan2882 — APPROVED** [review]
Thanks @ovindu-a !

**Comment by dartpain** [comment]
@holopin-bot @ovindu-a  Thank you!

**Comment by dartpain** [comment]
Hey @ovindu-a  please fill in this form if you are interested in a t-shirt
https://airtable.com/appikMaJwdHhC1SDP/pagoblCJ9W29wf6Hf/form

**Comment by ovindu-a** [comment]
Oh that's cool @dartpain. Thank you

**Pull request merged**
