### PR TITLE
fix: Enhance layout in Conversation components

### PR DESCRIPTION
**Pull request by SamsShow**
- **What kind of change does this PR introduce?**
fixes: 
1) 
image
2)
image
4)
image

- **Why was this change needed?** 
#1310

### CODE REVIEW

**Review by ManishMadan2882 — CHANGES_REQUESTED** [review]
Thanks @SamsShow 
Could you please check the avatar for mobile responsiveness.
image
Think it would be better if placed like the dino icon next to Answer.

**Comment by SamsShow** [comment]
@ManishMadan2882 
image
was working fine for a short message that's why I missed it. Will make the necessary changes

**Comment by SamsShow** [comment]
@ManishMadan2882 made the changes

**Review by ManishMadan2882 — CHANGES_REQUESTED** [review]
@SamsShow 
Sorry for not being clear before, only wanted the icon to be positioned like that on mobile screens, also the `Prompt` text is not required.
Just need a minor change to make the Avatar align as it was before 
* Small message
image
* Large message
image

**Pull request closed without merging**
