### PR TITLE
Fixed Responsiveness for Hero and Conversation

### PR DESCRIPTION
**Pull request by Vaibhav91one**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
    Bug fixes for Hero and Conversation component.

- **Why was this change needed?** (You can also link to an open issue here)
The UI was buggy when the sidebar closes for mobile screens.
https://github.com/arc53/DocsGPT/issues/1192

- **Other information**:
image

### CODE REVIEW

**Review by ManishMadan2882 — COMMENTED** [review]
Hi @Vaibhav91one 

Reviewed the changes, have few points:
1. The input box width planned to be wider as per the current UI design.
2. Tagline under the input box is supposed to be hidden in the mobile devices
3. The responsiveness issue in Hero and Conversations was recently solved in this [PR](https://github.com/arc53/DocsGPT/pull/1132), if it is specific to some tablets please mention.

Thank you!

**Comment by Vaibhav91one** [comment]
Hi @ManishMadan2882 

- Yes, I think the Height issue is fixed on the official website, 
- About the tagline I think it looks better in mobile also, if done correctly. 
- Lastly, When sidebar closes this is how it looks, which i think is a little off. 

Ultimately, Its your repo your rules. 😊

Official:
image

From my branch:
image

**Comment by ManishMadan2882** [comment]
Hi @Vaibhav91one 
Agree with the 3rd point, but we need to make sure that it doesn't affect the desktop version.
It looks like a issue in Tablet screens, also the tagline will be good to have in tab.
Thanks!

**Comment by Vaibhav91one** [comment]
> Hi @Vaibhav91one Agree with the 3rd point, but we need to make sure that it doesn't affect the desktop version. It looks like a issue in Tablet screens, also the tagline will be good to have in tab. Thanks!

HI @ManishMadan2882, So, the changes that will be done are done in previous PR in hero and conversation components. I will submit a new PR with the updated branch. Works?

**Comment by ManishMadan2882** [comment]
Absolutely @Vaibhav91one .

**Comment by shelar1423** [comment]
Hey @Vaibhav91one , there  is also a chance we would request you to fix as it aligns with the query bar issue.

image

Currently when we close the side bar and ask a query the query bar and the generated text arent aligned as shown in the picture.
So we need to fix this and make sure they are aligned.

**Comment by Vaibhav91one** [comment]
> Hey @Vaibhav91one , there is also a chance we would request you to fix as it aligns with the query bar issue.
> 
> image
> 
> Currently when we close the side bar and ask a query the query bar and the generated text arent aligned as shown in the picture. So we need to fix this and make sure they are aligned.

@shelar1423 , You mean the Answer and the ouput right?

**Comment by dartpain** [comment]
I think it looks like after sidebar is closed, the input box is not really centered, and that makes it mismatched with the output. Basically all things need to be aligned well here

**Comment by Vaibhav91one** [comment]
Please find the below PR for the changes.
[Pull Request](https://github.com/arc53/DocsGPT/pull/1287)

**Pull request closed without merging**
