### PR TITLE
Feat: enhance mobile responsiveness of Hero Page final

### PR DESCRIPTION
**Pull request by varundhand**
- **What kind of change does this PR introduce?** 
- This PR introduces a new **feature** to improve the **mobile responsiveness** of the website. 

- **Why was this change needed?** 
- Fixes issue #682 
- Previously, users had to **scroll down** on **mobile** devices to access the input field on the _home page_. This change enhances the user experience by ensuring that the input field is immediately visible, eliminating the need for unnecessary scrolling.

- **Other information**:
- _Before:_
Screenshot 2023-10-24 at 6 46 15 PM

- _After:_

Screenshot 2023-10-24 at 6 21 32 PM

### CODE REVIEW

**Comment by varundhand** [comment]
@dartpain is it fine now?

**Comment by dartpain** [comment]
Nearly done. But now this thing 
Screenshot 2023-10-31 at 17 27 42

Is broken on firefox. This bug was fixed recently, try to check out recent code for those boxes to make sure it does not break

**Comment by varundhand** [comment]
Hi @dartpain Its gonna be tough for me to fix it right now because I have my exams from tomorrow. Is it okay if I fix this within a few days? I have been working on it for two weeks now, why not give it a few more days lol

**Comment by dartpain** [comment]
Absolutely no worries, please take your time

**Comment by dartpain** [comment]
Good luck on your exams!

**Comment by varundhand** [comment]
@dartpain thank you so much! Also, will I be eligible for the swag now?

**Comment by dartpain** [comment]
There is a seven day period, until Noveber 7th we will review everything. 

Basically if you finish this PR and it works -> you will get the swag

**Comment by varundhand** [comment]
Sure thing, 7 days are more than enough! Thanks again!

**Comment by varundhand** [comment]
I fixed the container for firefox, it looks like this now:

Screenshot 2023-11-01 at 3 55 57 AM

**Review by dartpain — APPROVED** [review]

**Comment by dartpain** [comment]
Thank you! @holopin-bot @varundhand

**Pull request merged**
