### PR TITLE
UI bug fixed - Placed the feedback/copy buttons at the top

### LINKED ISSUE #536: 🐛 Bug Report: Like Dislike button in the message response should be at the top of the message bubble
## It makes it difficult for the user to locate the Like Dislike buttons
image
### 👟 Reproduction steps

I will place the buttons together at the top of the response message

### 👍 Expected behavior

The buttons associated with a particular message should be expected to be present at the top of the message, to make it more suitable for messages comprising long documentations.

### 👎 Actual Behavior with Screenshots

mobile (1)

### 💻 Operating system

Linux

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 🔒 Did you set the correct environment variables in the right path? List the environment variable names (not values please!)

API_KEY
LLM_NAME
VITE_API_STREAMING

### 📃 Provide any additional context for the Bug.

_No response_

### 📖 Relevant log output

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ManishMadan2882**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
     Makes the UI better by fixing the  position of Copy, Like, Dislike at the top of the message(answer or bot response)
- **Why was this change needed?** (You can also link to an open issue here)
     The Change fixes #536 
- **Other information**:
- A demo to the change
image

### CODE REVIEW

**Comment by ManishMadan2882** [comment]
I have raised the _**PR**_ @tenokami @dartpain

**Comment by tenokami** [comment]
@ManishMadan2882 Well done. Thank you

**Review by dartpain — APPROVED** [review]

**Comment by dartpain** [comment]
Thank you @ManishMadan2882 !

**Comment by ManishMadan2882** [comment]
_Thankyou_ @dartpain @tenokami

**Pull request merged**
