### PR TITLE
Feat implementation / #1020

### PR DESCRIPTION
**Pull request by blackviking27**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This PR is being made to implement the below feature
[https://github.com/arc53/DocsGPT/issues/1020](https://github.com/arc53/DocsGPT/issues/1020)

- **Why was this change needed?** (You can also link to an open issue here)
Implementing the following feature  [https://github.com/arc53/DocsGPT/issues/1020](https://github.com/arc53/DocsGPT/issues/1020)

- **Other information**:
Nope

### CODE REVIEW

**Review by ManishMadan2882 — CHANGES_REQUESTED** [review]
Perfect @blackviking27 ,
Requesting a minor change as mentioned in the issue:
* Please make sure that the three buttons for copy, like, dislike should be shifted to bottom of the response as in Mobile width.

Thankyou.

**Comment by blackviking27** [comment]
@ManishMadan2882 Should I remove the visible on hover functionality for the 3 icons. It is causing below ui issues

1. Only visible when we hover over the parent conversation bubble div and cannot click on it when mouse moves out of the bubble for computers
2. Overlaps with new conversation bubble as seen in the below image.

correct-search

**Comment by ManishMadan2882** [comment]
@blackviking27, 
Think that the overlapping can be fixed, and lets make sure that we require hover to display the icons for now.
Thankyou.

**Comment by blackviking27** [comment]
@ManishMadan2882 implemented the changes, please check and let me know if anything else is required

**Review by ManishMadan2882 — APPROVED** [review]
Perfect changes @blackviking27
Thankyou!

**Pull request merged**
