### PR TITLE
Update API-docs.md

### PR DESCRIPTION
**Pull request by HarshMN2345**
done all the changes proposed in issue #508

### CODE REVIEW

**Comment by HarshMN2345** [comment]
@dartpain done all the changes proposed in issue #508

**Comment by dartpain** [comment]
I think out of 3 changes made only "While the task is still running, the 'current' value will show progress from 0 to 100." part is useful. Can you please remove others.

Also I dont think its a good place for users to be redirected to a place to learn about vectorstores.
Thank you!

**Comment by HarshMN2345** [comment]
@dartpain done

**Comment by dartpain** [comment]
@HarshMN2345 I would suggest to try to look into similarity search first, cosine similarity and so on. Once you understand it, its pretty much a database for those.

Thank you, can you remove the link as requested please.

**Comment by HarshMN2345** [comment]
@dartpain done

**Comment by dartpain** [comment]
This is a non clickable link
Screenshot 2023-10-11 at 18 54 30

**Review by dartpain — APPROVED** [review]

**Comment by dartpain** [comment]
Thank you!

**Pull request merged**
