### PR TITLE
Add slack integration

### LINKED ISSUE #1290: 🚀 Feature: Slack extension
### 🔖 Feature description

Slack extension for docsgpt, should connect with docsgpt chatbot api

### 🎤 Why is this feature needed ?

To integrate docsgpt with slack

### ✌️ How do you aim to achieve this?

Here is an example of a good extension:
https://github.com/arc53/DocsGPT/tree/main/extensions/react-widget
Also this:
https://github.com/arc53/tg-bot-docsgpt-extenstion

Should include history management ideally and display sources too (in very minimised way)

### 🔄️ Additional Information

_No response_

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

### PR DESCRIPTION
**Pull request by mousumi2002**
- **What kind of change does this PR introduce?**
Feature

- **Why was this change needed?**
Resolves #1290

- **Other information**:
    @ManishMadan2882 I have added initial support for a Slack bot integration. Here's what is currently supported as a part of the integration. 
    
    - DM the chatbot to get a response
    - Show message loading status using Slack's inbuilt setThreadStatus function
    
    I need more clarity on the following stuff:
    
    - Do you need any additional functionalities added
    - The DocsGPT API supports history passing. In Slack, if we use the bot in a channel, it isn't wise to query chats as it will breach privacy. If used in threads, I have yet to find a method to get the history for a thread. For this feature, is history passing an essential requirement?
    
    Things I would be working on after the initial review:
    
    - Documentation
    - Creating setup instructions in `readme.md`

### CODE REVIEW

**Review by ManishMadan2882 — CHANGES_REQUESTED** [review]
Perfect @mousumi2002, followed the README and it works fine.
image
Requesting a minor change to remove source_id from the payload in generate_answer method as the `/api/answer` doesn't expect a `source_id`.
Regarding the history support, I don't think that there is any concern of privacy breach with Chatbots, however this won't be needed in the initial version of slack extension.
Thank you !

**Review by ManishMadan2882 — APPROVED** [review]
Thanks for the update!

**Comment by dartpain** [comment]
@holopin-bot @mousumi2002

**Comment by dartpain** [comment]
And a special api holopin!
@holopin-bot @mousumi2002 api

**Pull request merged**
