### PR TITLE
docker docs

### PR DESCRIPTION
**Pull request by krishvsoni**
- **What kind of change does this PR introduce?**  - docs update -
-  **Why was this change needed?** (You can also link to an open issue here
- ) Already yaml file of docker is given but it in quick start we need to give Docker official url for downloading according to user device. It will help to setup the docker will also save the time 

- **Other information**: - image

### CODE REVIEW

**Comment by dartpain** [comment]
Thank you so much for your PR. But unfortunately I cannot accept this PR. Can you explain what changes you are making?

**Comment by krishvsoni** [comment]
> Thank you so much for your PR. But unfortunately I cannot accept this PR. Can you explain what changes you are making?

I did a very minor change in the Readme File in the docker i had given the documentation url for that. For the user reference and setup. I had some conflicts in branch but i had resolved it.

**Comment by dartpain** [comment]
Looks like there are still some differences, I think you merged with older version. Can you please resubmit this PR. Just try forking again please

**Comment by krishvsoni** [comment]
https://github.com/arc53/DocsGPT/pull/675

I Pull request again

**Pull request closed without merging**
