### PR TITLE
Modified README resolving issue #457

### PR DESCRIPTION
**Pull request by alienishi**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This PR introduces an updated version of the README.md file, resolving issue #457 i.e store -> storage
- **Why was this change needed?** (You can also link to an open issue here)
Issue #457 
- **Other information**:

### CODE REVIEW

**Comment by alienishi** [comment]
@dartpain
Can you please add the Hacktoberfest-accepted label to this assessment , My contribution will not be accepted in Hacktoberfest if the label is absent. Thanks :)

**Comment by dartpain** [comment]
It will count towards your score even if its not labelled
Also its not really storage. Just remove "and storage" part

**Comment by alienishi** [comment]
@dartpain I have made the changes suggested by you.
Please review it and if according to the guidelines then please do merge it 
It will help me in hacksquad :)

**Review by dartpain — APPROVED** [review]

**Comment by dartpain** [comment]
@holopin-bot @alienishi

**Pull request merged**
