### PR TITLE
Table Styling & Add search feature to backend

### PR DESCRIPTION
**Pull request by fadingNA**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- #1440 

- **Why was this change needed?** (You can also link to an open issue here)
uniform table nicely

- **Other information**:
update table styling uniformly

@ManishMadan2882 

Screenshot 2024-11-15 at 11 17 28 PM

### CODE REVIEW

**Comment by fadingNA** [comment]
@ManishMadan2882  update table

**Comment by fadingNA** [comment]
@ManishMadan2882  please review have change and fix bug on sort order, and use effect behavior

**Comment by fadingNA** [comment]
@ManishMadan2882  update white color on darkmode when no data and api. 

align table using same format both apikey , document

**Comment by ManishMadan2882** [comment]
@fadingNA The settings/documents is scrollable even when it is not required(basically there is empty space below).
Ideally this shouldn't be there,
Could you please check.
Thanks!

**Comment by fadingNA** [comment]
@ManishMadan2882  let me check

**Review by ManishMadan2882 — APPROVED** [review]
LGTM,
Thank you @fadingNA !

**Comment by fadingNA** [comment]
> LGTM, Thank you @fadingNA !

Appreciate it @ManishMadan2882  @dartpain

**Pull request merged**
