### PR TITLE
fix: #1219 Too big top margin of message box separator

### PR DESCRIPTION
**Pull request by AkashJana18**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fixes: #1219 

Before : 
image

After:
image

- **Why was this change needed?** (You can also link to an open issue here)
Better UI/UX
- **Other information**:
Feel free to ask if anymore changes required

### CODE REVIEW

**Comment by AkashJana18** [comment]
Hey @ManishMadan2882 @tenokami can you please take a look?

**Comment by tenokami** [comment]
@AkashJana18 Great change! Thank you

**Comment by AkashJana18** [comment]
Hey @tenokami can you merge it as well, as today all the fest are ending. I would be glad if it merged before the fest ends.

**Comment by ManishMadan2882** [comment]
Hi @AkashJana18 
please check the overflow in input text
image
Also the height of input box has changed.
Thanks

**Comment by AkashJana18** [comment]
image
image

**Review by ManishMadan2882 — CHANGES_REQUESTED** [review]
@AkashJana18 
The scrollbar is removed from the input box, please check it once with larger inputs.
image
Thanks!

**Comment by AkashJana18** [comment]
I have made the requested change @ManishMadan2882 can you please review it?

**Review by ManishMadan2882 — APPROVED** [review]
Thanks @AkashJana18 !

**Pull request merged**
